### ISSUE TITLE
Packages created from repos on the Emacsmirror

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#1036]
I asked @purcell elsewhere what packages were created from repositories an the Emacsmirror and then looked into how popular these packages are and how they get into the Emacsmirror:

### DONE removed since in GNU Elpa
* [x] csv-mode
* [x] sml-mode

### DONE get from new upstream
* [x] ssh-config-mode

### DONE part of bigger repository
The Emacsmirror's basic unit is the repository. It cannot split that up into individual packages like Melpa does.
* [x] shimbun (w3m)

### TODO no longer updated and popular
Contact upstream and/or add to Emacsorphanage.
* [ ] crontab-mode (2132)
* [ ] session (2687)
* [ ] smarty-mode (2039)

### HOLD no longer updated and obscure
* [ ] dedicated (87)
* [ ] keydef (71)
* [ ] log4j-mode (181)
* [ ] pager (61)

### TODO currently not updated from plain files and popular
Contact upstream and/or add to Emacsorphanage.
Importing from plain files is currently broken on the Emacsmirror.
This will eventually be fixed but not very soon.
* [ ] diminish (7183)
* [ ] hl-sexp (1970)
* [ ] mwe-log-commands (2372)
* [ ] pointback (2039)
* [ ] textile-mode (2144)

### HOLD currently not updated from plain files and obscure
Importing from plain files is currently broken on the Emacsmirror.
This will eventually be fixed but not very soon.
* [ ] edit-list (107)
* [ ] escreen (162)
* [ ] fm (110)
* [ ] fold-dwim (328)
* [ ] osx-plist (152)
* [ ] parenface (242)
* [ ] psvn (205)
* [ ] revive (256)
* [ ] xterm-frobs (46)

----

**Edit**: added missing information
**Edit 20140627**: mark some things as done
**Edit 20141104**: note that plain file import is broken

**Comment by milkypostman** [comment]
Will close this. Because I am unclear on if this er relevant anymore. @tarsius please reopen if you feel this is still relevant.

**Comment by Silex** [comment]
I came here because `crontab-mode` does not exist anymore. What is the `TL;DR;` version about it? Should I copy it locally in my emacs config?

**Comment by purcell** [comment]
> What is the TL;DR; version about it? Should I copy it locally in my emacs config?

There's no known current maintainer, or person able to assign copyright to the existing code. So probably yes.

**Comment by Silex** [comment]
Alright, thanks :smile:
