### ISSUE TITLE
Improve website render performance

### ISSUE THREAD

**Issue by nicwins** [milkypostman/melpa#1326]
Currently the project list portion of the website takes (in chrome) ~3 seconds to load and ~2 seconds to sort/filter.  As the number of packages increases this is only going to get worse. I think this could be dramatically improved by either: 

* replacing the html table with [ng-grid] (http://angular-ui.github.io/ng-grid/) 
* taking it out of the ng-repeat and building the table up from fragments in a directive

If this won't mess up any current plans for the website, I'll volunteer to do it.

(It might also be a good idea to debounce the filter input and sort headers, as clicking a few times in frustration can lead to a 30s block while rendering)

**Comment by milkypostman** [comment]
obsolete.
