### ISSUE TITLE
bbdb version is not correct

### ISSUE THREAD

**Issue by brabalan** [milkypostman/melpa#1470]
When installing bbdb through melpa, the version number is not substituted.

To reproduce, install bbdb and type "M-x bbdb-version". The current output is:

```
BBDB version @PACKAGE_VERSION@ (@PACKAGE_DATE@)
```

This is unfortunate as some other packages (like icicles) rely on the version number to decide how to interact with bbdb.

Could this version be substituted when installed through melpa?

**Comment by milkypostman** [comment]
Closing this because we have #750 to track the actual issue.
