### ISSUE TITLE
ESS on MELPA stable returns 404

### ISSUE THREAD

**Issue by phillord** [milkypostman/melpa#1729]
Not sure if this is the right place for MELPA stable issues! If not apologies. 

The link in question is:
http://melpa-stable.milkbox.net/packages/ess-13.9.tar

It fails on the website and inside Emacs

The stable idea is fantastic BTW. I use Emacs on several machines, so on bleeding edge melpa, I ended up with a slightly different version of the various packages I used, which didn't work for me. For me, reliable and repeatable are the big wins!

**Comment by sje30** [comment]
Hi @purcell @milkypostman 

ESS is now on github and our releases are tagged, e.g.:

so our latest version is 15.03 (see below).  As well as having ESS on melpa, can you help us get ESS on melpa-stable?

```
 git tag
spinuvit_first
swank_funcs
v12.03
v12.04
v12.04-1
v12.04-2
v12.04-3
v12.04-4
v12.09
v12.09-1
v12.09-2
v13.05
v13.09
v13.09-1
v14.09
v15.03
```

**Comment by sje30** [comment]
p.s. @phillord Is this still desirable for you to have ESS stable versions on here?

**Comment by sje30** [comment]
Oops, very sorry!  I see we are already on stable!  Thanks to @vspinu  for pointing this out to me.
