### ISSUE TITLE
Question to add recipes of ERFI and jumar

### ISSUE THREAD

**Issue by kenoss** [milkypostman/melpa#2248]
Hello, I'd like to ask two questions to apply two my packages ERFI and jumar.

ERFI

A brief summary of what the package does: A set of libralies like SRFI in Scheme, which contains named let with tail recursion optimization.

A direct link to the package repository: https://github.com/kenoss/erfi

Your association with the package: Author

Jumar

A brief summary of what the package does: A new jump and marker environment, which enables emulate those in Vim.

A direct link to the package repository: https://github.com/kenoss/jumar

Your association with the package: Author

ERFI is used some packages I wrote.  Jumar also depends on it.

First question: ERFI is a set of libraries and there isn't `erfi.el`.  So AIU we can't write in header of `jumar.el` as the following:

```emacs-lisp
;; Package-Requires: ((emacs "24") (cl-lib "0.3") (erfi "0.1"))
```

How should I write down such dependency?  Where should I write version information of ERFI?

Second question: Jumar provides visualizer using helm.  This is optional and the other part doesn't depend on helm.  However, a minor feature does not work correctly without recent version of helm.  I do not want to force users to install helm unless they use visualizer.  How should I write this dependecy?  I accept raising errors for this feature without recent version of helm if there's no good way, because this is a minor feature.

Sincerely.

**Comment by purcell** [comment]
Any word on this?

**Comment by purcell** [comment]
In fact, I'll close this issue, but feel free to ask further questions here. Once any corresponding changes are made, you should submit a PR with recipe definitions which you've tested locally following the directions in the README. Thanks!
