### ISSUE TITLE
Rendering of chinese characters in package list

### ISSUE THREAD

**Issue by purcell** [milkypostman/melpa#2313]
`chinese-fonts-setup` has the description "实现中英文字体等宽对齐的字体配置工具。", and it is encoded in UTF-8 into our `archive-contents` file. In the package list, it is displayed as backslashed numeric byte codes. This is presumably because we serve `archive-contents` as `application/octet-stream`, and Emacs then applies a default coding system to it.

So 2 things:

1. We should serve `archive-contents` with a `text/plain` MIME type, and UTF-8 content-encoding.
2. We should ensure that we explicitly use UTF-8 throughout the MELPA process so that any such character like this are handled correctly -- we can't rely on upstream authors using UTF-8 in their source files.

**Comment by xuchunyang** [comment]
@purcell Do you mean we cannot use Chinese characters in package description? Does other ELPA  have this limitation?

I have one package with some Chinese characters in tis [description](https://github.com/xuchunyang/helm-zhihu-daily/blob/master/helm-zhihu-daily.el#L1), these Chinese characters cannot be displayed properly, but it works fine when I installed that package locally via `package-install-from-buffer`.

**Comment by purcell** [comment]
@xuchunyang No, there's no problem now: your package and others like it should work fine now.

**Comment by xuchunyang** [comment]
but I still get this when I run `M-x package-list-packages`:

![screen shot 2015-03-30 at 3 55 18 pm](https://cloud.githubusercontent.com/assets/4550353/6892271/49ae2a76-d6f5-11e4-8fff-78eafac1e42a.png)

Am I missing anything?

**Comment by purcell** [comment]
Ahh, true. Me too. I'll investigate later.

**Comment by purcell** [comment]
Okay, so the `archive-contents` file contains properly UTF8-encoded chars, but `package.el` is obviously just reading it in and interpreting its encoding differently. So this is either a bug in `package.el`, or (more likely) we need to work around its current behaviour.

**Comment by purcell** [comment]
Filed for discussion here: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20231

**Comment by purcell** [comment]
This was fixed upstream in Emacs. There is no backported fix for older Emacs versions, unfortunately.

**Comment by xuchunyang** [comment]
Thank you.  I noticed a few days ago by using emacs trunk.

**Comment by tumashu** [comment]
good job!
