### ISSUE TITLE
request to rm wiki.el recipe

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#2341]
It's not available anymore but could possibly be as a result of the outage. thinking we should remove it anyways because according to the [Wiki Modes](http://www.emacswiki.org/emacs/WikiModes) page it's abandonware anyways.

**Comment by milkypostman** [comment]
@Wilfred your package contribution.

**Comment by Wilfred** [comment]
No worries here. I abandoned it when it didn't work with Emacs 24.4 -- I still think it's a neat little project, just providing links without fuss, but I don't actually use it any more.
