### ISSUE TITLE
speechd-el should be renamed to speechd

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2345]
The main library is named `speechd.el` so to package should be named `speechd`. Unfortunately the pkg file is `speechd-el-pkg.el`, not sure whether you can just ignore that.

**Comment by purcell** [comment]
Agreed, but this is an issue for the author at this stage, not MELPA. Right now we're getting the package metadata from that `-pkg.el` file, so while not ideal, things are working okay from a MELPA point of view. Ideally we'd have demanded the change before adding it...

**Comment by tarsius** [comment]
Yep that should be fixed upstream. But let's keep a list here:

* [ ] speechd-el => speechd
* [ ] ddskk => skk

**Comment by tarsius** [comment]
I have send an email to upstream.

**Comment by tarsius** [comment]
Upstream wants to keep the current name.

**Comment by purcell** [comment]
Ah well. Thanks for trying.
