### ISSUE TITLE
Badge images broken

### ISSUE THREAD

**Issue by luismbo** [milkypostman/melpa#2346]
The badge URLs appear to be broken.

    $ wget http://melpa.org/packages/magit-badge.svg
    --2015-01-04 01:23:59--  http://melpa.org/packages/magit-badge.svg
    Resolving melpa.org... 104.236.16.183
    Connecting to melpa.org|104.236.16.183|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2015-01-04 01:23:59 ERROR 404: Not Found.

**Comment by milkypostman** [comment]
sorry about that, should be fixed now.

**Comment by luismbo** [comment]
@milkypostman oh, but that way #2231 breaks again.

**Comment by luismbo** [comment]
Hmm. I'm seeing the "Cache-Control: no-cache" header. So you must have solved that somewhere else. Thanks! :-)

**Comment by milkypostman** [comment]
Yeah. The problem was that I added a badge related line to the proxy
config. But it needed to go on the config of the actual server. No worries.
So everything is working as you hope now?

**Comment by luismbo** [comment]
I'm confused by your explanation because commit https://github.com/milkypostman/melpa/commit/6315eda0a7b4a968b076bb79d8296a0777b11293 seems to remove the configuration from the server. (I'm assuming that the "actual server" refers to the nginx server.)

But, to answer your question: yes, things appear to be working:

    $ curl -D - http://melpa.org/packages/slime-badge.svg
    HTTP/1.1 200 OK
    Server: nginx/1.4.6 (Ubuntu)
    Date: Mon, 05 Jan 2015 23:45:28 GMT
    Content-Type: image/svg+xml
    Content-Length: 835
    Connection: keep-alive
    Last-Modified: Mon, 05 Jan 2015 22:38:38 GMT
    ETag: "54ab126e-343"
    Cache-Control: no-cache
    Accept-Ranges: bytes
    ...

ETag and Cache-Control headers are there and that's what's needed to avoid GitHub's aggressive image caching.

Thanks!
