### ISSUE TITLE
badges not refreshing on github

### ISSUE THREAD

**Issue by fommil** [milkypostman/melpa#2356]
:cry: We have a lot of new releases in December 2014 and January 2015 but our badge still shows up as November 2014 https://github.com/ensime/ensime-server

It looks like github is caching the image and not aware that it is dynamic. Maybe something to do with cache flags?

**Comment by milkypostman** [comment]
@fommil this sounds like #2346 which is fixed now. I just loaded your page and I see the 2015 one. It seems like maybe before we fixed the other issue you pulled it and your browser cached it, not knowing it shouldn't. And now you will have to hard refresh that image.

**Comment by fommil** [comment]
:smile:
