### ISSUE TITLE
Should ddskk be renamed to skk?

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2379]
While the name of the project is Daredevil SKK, they don't provide `ddskk`, just `skk`.

**Comment by purcell** [comment]
IIRC there's a `ddskk-pkg.el`, though, so I'm fine with this.

**Comment by purcell** [comment]
I believe I added the package as `skk`, and then it was later renamed both in MELPA and via `skk-pkg.el` -> `ddskk-pkg.el`.

**Comment by tarsius** [comment]
@skk-dev Could you please consider renaming the package `ddskk => skk` or renaming the library `skk.el => ddskk.el`? While it is not mandatory, I think it is still a good idea if the name of the package and the (main) library match.

**Comment by tarsius** [comment]
Well, I don't insist.
