### ISSUE TITLE
Simple Emacsql database for Melpa

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2394]
While searching Melpa for packages which should also be added to the Emacsmirror, I have created [`melpa-db.el`](https://github.com/tarsius/melpa-db). It stores the Melpa recipes in an SQLite database accessed using Emacsql and provides a command to list them similar to what `list-packages` does.

This was adapted from `epkg.el` which is part of the toolchain used to maintain the Emacsmirror (and hasn't been released yet). Also included is `melpa-vs-epkg.el` which contains lists of packages which are intentionally not mirrored and tools to augment the Melpa database with that information. The latter doesn't work without `epkg.el` but the lists might still be interesting.

I though I would share this with you, in case you can find some use for it.

To use, first remove all trash using `git clean -fdx recipes`, then customize `melpa-db-file` and `melpa-db-recipe-directory`, and create the database using `M-x melpa-db-recreate`.

**Comment by purcell** [comment]
Ah, nice! There's also a json version of the recipes, btw, at http://melpa.org/recipes.json. Hey, I really like that `slot-missing` trick: I've never seen `method-missing` done in a lisp before.

**Comment by milkypostman** [comment]
I have no idea what any of this code is doing.

eieio

**Comment by tarsius** [comment]
> eieio

clos

> I have no idea what any of this code is doing.

It doesn't really do much, it just provides a solid foundation to build stuff on top. It does provide access to a SQLite database and tools for converting back and forth between db rows and clos objects. There's also an importer for the recipe files and my lists of differences between Melpa and the Emacsmirror.

At the end of the file you'll find a feature which is useful on its own - listing all the recipes using `tabulated-list-mode`. That alone doesn't really justify the preceding complexity, then again this is just a port of a tool I use for the Emacsmirror, and that tool builds a lot off functionality on top of this.

**Comment by tarsius** [comment]
Closing. You know where you kind find me if you want to use this and need my help :-)

**Comment by purcell** [comment]
Thanks Jonas. I can imagine using this for certain tasks in future.
