### ISSUE TITLE
pyregexp's upstream repository has gone missing

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2418]
It used to be at https://github.com/benma/pyregexp.

@benma What happened to it?

**Comment by benma** [comment]
pyregexp's recipe has been deleted over a year ago in #1291. I recently deleted the repo.

pyregexp has been deprecated for a long time. Its functionality is a subset of the maintained packages [visual-regexp](https://github.com/benma/visual-regexp.el) and [visual-regexp-steroids](https://github.com/benma/visual-regexp-steroids.el). The former provides the visual feedback functionality (with Emacs' regexp), the latter provides the Python and pcre2el engines.

**Comment by tarsius** [comment]
Ups sorry, I overlooked that it was already removed :-/

**Comment by benma** [comment]
Np. If you were using pyregexp until now, I suggest you switch to the successors. It's a better experience all around.
