### ISSUE TITLE
Ability to download all MELPA packages without installing them?

### ISSUE THREAD

**Issue by flexibeast** [milkypostman/melpa#2430]
i've written a Perl5 script to do a basic/naïve static analysis of the usage of certain libraries by ELisp packages. In particular, what i'd like to do is download all packages from MELPA, without installing them, so that i can use my script to examine usage of the `dash` and `s` libraries and the functions therein. (Using `package.el` to download-and-install all of MELPA presents problems, such as `org-outlook` not being able to be installed successfully on my non-Win system.)

Is there some way to download all .tar.gz and .el files from melpa.org/packages?

**Comment by milkypostman** [comment]
i don't want to condone any particular process for this but you could easily write a script to fetch all the packages based on the frontend code. Have a look at the javascript and you should be able to see how we generate our links and from there you can get a link to every file...

remember that we pay for hosting :)

**Comment by flexibeast** [comment]
Oh, so are your hosting costs based on data transferred by site users, as per [the NFSN model](https://www.nearlyfreespeech.net/services/pricing)? If so, is there some way i could cover the costs of the bandwidth required for a single download of the entirety MELPA? i can't see myself wanting to continually download everything - in fact, i'm basically thinking of this as a once-off - but i do think doing this analysis might provide some data about which functionality perhaps should/shouldn't be included in Emacs itself.

**Comment by purcell** [comment]
@flexibeast If you just want to find which packages *depend* on `dash`, `s` etc., then consider just inspecting http://melpa.org/archive.json.

**Comment by flexibeast** [comment]
@purcell:

No, i'm actually wanting to analyse which *specific* functions in `dash` and `s` get used, and to what extent, to get a sense of which functions might indeed be sufficiently in demand to consider including them in Emacs core. (But my Perl5 script is generalised such that usage of functions in other libraries could be analysed as well - i'm planning to make the script more generally available.)

**Comment by purcell** [comment]
Makes sense. You could reconstruct the necessary download URLs using `archive.json`. Alternatively, you could just run the whole MELPA build locally.

**Comment by milkypostman** [comment]
I'm not worried about bandwidth too much. It's a monthly chunk of
bandwidth. But just don't want it to go crazy.

**Comment by flexibeast** [comment]
@purcell:

i ended up running the whole build locally. :-) Thanks!

**Comment by purcell** [comment]
Great, glad you got it working. Will be interested to see what you discover. :-)
