### ISSUE TITLE
defconst package compilation problem

### ISSUE THREAD

**Issue by reactormonk** [milkypostman/melpa#2476]
The [nim major mode](https://github.com/reactormonk/nim-mode/blob/master/nim-mode.el) works well if loaded via file, `byte-compile-file` works fine too, but when loading in via elpa, it doesn't compile:

    Compiling file /home/steve/.emacs.d/elpa/nim-mode-20150203.802/nim-mode-pkg.el at Tue Feb 3 21:48:51 2015
    Entering directory `/home/steve/.emacs.d/elpa/nim-mode-20150203.802/'

    Compiling file /home/steve/.emacs.d/elpa/nim-mode-20150203.802/nim-mode.el at Tue Feb 3 21:48:51 2015
    nim-mode.el:184:1:Error: Symbol's value as variable is void: nim-keywords

Original issue: https://github.com/reactormonk/nim-mode/issues/16

I have no idea what could cause the problem, so I'm looking for help here.

**Comment by purcell** [comment]
See my comment on that issue: will close this. :-)
