### ISSUE TITLE
skeletor installer should not compile the template elisp files.

### ISSUE THREAD

**Issue by MassimoLauria** [milkypostman/melpa#2484]
I am not sure whether this is a melpa recipe issue or an upstream issue. 

The `skeletor` package includes project templates for, among others, emacs packages. The templates contain stub elisp files that should be included in the package, but should not be compiled during package installation. 

Currently these stub files are compiled causing warnings and, *worst of all*, producing spurious *.elc files to be included in the project template.

**Comment by purcell** [comment]
This would be an issue for @yasuyk upstream. The stub files should be marked with the `no-byte-compile` local variable if they are not to be compiled. This can be achieved via a `.dir-locals.el`, which I think would then be honoured by `package.el` at installation time.
