### ISSUE TITLE
Advice on making more than one package version available

### ISSUE THREAD

**Issue by Bruce-Connor** [milkypostman/melpa#2494]
I've recently had to drop support for Emacs 24.3 on paradox master branch, and I'll soon tag that as `2.0`. Once I do that, IIUC, when a user calls `list-package` on Emacs 24.3 he'll be offered a version of Paradox that is uninstallable. What's worse, I think this package will be marked for upgrade whenever the user hits `U`, which would throw an error every time and probably eventually lead the user to uninstall the package. (Technically, this is already happening with the unstable version, but I'm fine with that.)

This is mostly a bug in `package.el`, but (given that there's no chance of this being fixed in 24.3) I was wondering if the fine fellas at melpa knew of a workaround for it.

Furthermore, is there a way to make the old (1.0) version still available to older emacs once the new (2.0) version is released?

**Comment by milkypostman** [comment]
If the stable version gets a tag, then it will be built on melpa-stable.
I'm not sure, other than that, how to make multiple packages available.
What you could do is just update your README to note that a 24.3 version of
the package is available on melpa-stable. But since 24.4 is out, I don't
think this is a major issue, except for people using ubuntu LTS where it's
stuck at like 24.2.

Was it completely necessary to drop 24.3 support?

**Comment by Bruce-Connor** [comment]
Ok. Thanks for the reply (and sorry for leaving this hanging). 
Dropping 24.3 support wasn't completely necessary, but it was holding back development and (most importantly) was taking the fun away from it. =/ It was a difficult choice, but if I hadn't done it Paradox would have stayed stuck where it was.

In any case, I think I'll just create a separate repository and submit a new package called `paradox-24.1-24.3` (or something like that) which would hold the old version and explain that in the description. Would that be acceptable by Melpa standards?

**Comment by purcell** [comment]
> In any case, I think I'll just create a separate repository and submit a new package called paradox-24.1-24.3 (or something like that) which would hold the old version and explain that in the description. Would that be acceptable by Melpa standards?

This isn't really an unusual situation. What you're proposing seems like a hack, and I can't see that it's going to help in any tangible way. You're presumably worried about `paradox` users who currently use older versions of Emacs: well, they will just have to avoid upgrading, or you can point them at an old version in github and tell them to download and install it manually with `package-install-file`.

Please correct me if I'm misunderstanding this.

**Comment by Bruce-Connor** [comment]
Kind of... I'm worried about 2 things 

1. If a user of 24.2 already has an old version, Paradox will be marked for upgrade whenever he hits U in the package menu. The upgrade will always fail because a dependency can't be satisfied, and the user will eventually get tired of this and just uninstall the package.

2. A new user (also on 24.2) might run into Paradox on the package menu and try to install it. Once it fails, they won't know there is an older version available on the website, so they'll just give up.

I understand neither of these are within Melpa's power, and there's not much I can do to avoid them either. But I can make an old version available on the Package Menu, so that these users who don't check the website might still realise that this version exists.
It would also allow me to more easily deliver an occasional bug fix.

---

Actually, I just thought of a second option. I might copy-paste the old code into an extra file on the current package, and load that file (and only that file) on older emacs versions. 

I'll have to do some patching for the autoloads, but at least it should allow me to keep this old version around without having to develop it.

**Comment by purcell** [comment]
> Actually, I just thought of a second option. I might copy-paste the old code into an extra file on the current package, and load that file (and only that file) on older emacs versions.
> 
> I'll have to do some patching for the autoloads, but at least it should allow me to keep this old version around without having to develop it.

Yeah, keeping the package backwards-compatible is always a good option. :-)

**Comment by milkypostman** [comment]
In general, I am personally OK with requiring the newest release of Emacs.
BUT, that can be annoying to some people. So my general guideline is the
version released with the latest Ubuntu release; not LTS.

However, backwards compatibility is always nice. So if you can just provide
a small change in the package to make it work with older versions, that
would be good.

**Comment by Bruce-Connor** [comment]
Ok. Thanks for the chat. I'll close this for now. 
I'm still unsure how much trouble autoloads will give me, but I'll give it a try.
