### ISSUE TITLE
Web UI: Can't paginate search results

### ISSUE THREAD

**Issue by Wilfred** [milkypostman/melpa#2509]
When searching for 'ht' with pagination enabled on http://melpa.org/#/, the web page says '138 matching packages' but the pagination only offers me a single page. As a result, the package 'ht' (and many other packages) can't be seen without disabling pagination.

**Comment by purcell** [comment]
Doh. Haven't seen that before. Will investigate tomorrow.

**Comment by purcell** [comment]
Was a silly mistake on my part. Will be fixed when the next build cycle refreshes the site.
