### ISSUE TITLE
Handling full rename of existing MELPA package

### ISSUE THREAD

**Issue by flexibeast** [milkypostman/melpa#2514]
Having learnt that there's PicoLisp support for Emacs predating my own [`picolisp-mode`](https://github.com/flexibeast/picolisp-mode) package, i've decided to rename my package to `a-picolisp-mode`. To that end, in my local repo, i've renamed the `picolisp-mode.el` file to `a-picolisp-mode.el`, and modified all `picolisp-` symbol prefixes to `a-picolisp-` prefixes.

How should i proceed from here, in order to cause the least disruption to my users, and the least hassle for the MELPA team? Reading over issue https://github.com/milkypostman/melpa/issues/956, it seems that this renaming is more extensive, and might involve more than simply changing the repo name and its MELPA recipe ....

**Comment by purcell** [comment]
Hi! I don't see any renaming in your repo yet. If you decide to proceed, we'd need to rename the file, the symbols inside it, and the MELPA recipe. We'd probably also add `:old-names (picolisp-mode)` to the recipe, so that we can handle download totals and redirects from the old page correctly.

But where is this precursor? Is it better than your package? Is it in a package archive somewhere? Does this really matter right now?

**Comment by flexibeast** [comment]
> Hi! I don't see any renaming in your repo yet.

Not in the online repo; as i wrote above, i've only made the changes in my local (i.e. "on my laptop") repo. i haven't pushed those changes yet as i didn't a new MELPA package to be automatically built from them without having first discussed with the MELPA team how to handle this situation.

> But where is this precursor? Is it better than your package? Is it in a package archive somewhere?

There are two versions available; one is bundled with the PicoLisp distribution ([here](http://software-lab.de/down.html)), and the other is a modified version of that ([here](https://github.com/tj64/picolisp-mode)). The former apparently hasn't been tracking the latter; and the latter hasn't been updated in a couple of years, with its official maintainer effectively offline at the moment. The existence of the former bundle isn't mentioned anywhere (as far as i can tell) in [the PicoLisp documentation](http://picolisp.com/wiki/?Documentation), and the latter bundle isn't available via any ELPA, which is why i ended up writing my own package, as i didn't realise these two things existed.

As for which of the three bundles is 'better', well, i guess that depends on the criteria one uses. My posts to [this thread](http://www.mail-archive.com/picolisp@software-lab.de/msg05136.html) show some of the issues with the precursor bundles; i'll copy and paste my most recent post to this thread, as it seems to have got mangled somewhere between my MUA and the list:

--- BEGIN email ---

    On 2015-02-17T17:12:54+1100, Alexander Burger said: 

     AB> as I mentioned in my previous mail, is Thorsten currently
     AB> offline.  He asked me to post this for him

       A> "i'll try to find some time to: 

       A> * examine the diffs between the distribution version and the 
       A> GitHub version; 

      TJ> Why? Just use the newer version, i.e. the Github
      TJ> version. Nobody else but me did change anything recently. 

    Then why isn't the GitHub version the one currently distributed 
    with PicoLisp? The fact that it's not suggested to me there might 
    be some issues around doing so. And why does the distribution 
    version contain picolisp-wiki-mode.el, whereas the GitHub version 
    doesn't?   (A separate issue is, why do users have to manually 
    patch  paredit.el?  Has there been some issue with upstream not 
    being  willing or able to modify paredit.el so that it can better 
    support  PicoLisp?) 

       A> * add to the former any fixes and/or extra functionality
       A> found in the latter; 

      TJ> Again - why? Just replace the older version with the
      TJ> newer version ... 

    See above. 

       A> * add in my code to present documentation for the symbol at 
       A> point; 

      TJ> and you mean an eldoc implementation for picolisp? 

    No, although that's certainly a good idea. What my code does is 
    (for Emacs > 24.3) to open the full reference documentation for a 
    particular function in a new buffer via `shr`, or (for Emacs < 
    24.4) in a Web browser. 

      TJ> patches are welcome, just fork me on github. 

    .... except you're currently offline, for a period of time not 
    specified. As i've mentioned elsewhere in this thread, given my 
    experiences of spending time coding and submitting PRs/issues, 
    only to have the latter ignored even by people who are 
    demonstrably still actively coding, i'm not much inclined to get 
    involved with code whose maintainer is very explicitly offline. 

       A> * add in things like user configuration of the path to the 
       A> `pil` executable.  :-)" 

      TJ> AFAIK the path is remembered, to avoid typing, but can be 
      TJ> changed - just try using a prefix before the command, that 
      TJ> should give you the opportunity to type in your own path 
      TJ> (but I'm not sure right now). 

      TJ> Try C-h f on the core functions, there is quite a lot of 
      TJ> info in the docstrings. 

    Here's the doc for `run-picolisp` (which, i note, isn't mentioned 
    in the README; nor does it begin with the `picolisp-` prefix to 
    assist its discoverability and limit namespacing issues) from the 
    GitHub version: 

        run-picolisp is an interactive autoloaded Lisp function in 
        `inferior-picolisp.el'. 

        It is bound to <run-picolisp>. 

        (run-picolisp CMD) 

        Run an inferior Picolisp process, input and output via buffer 
        `*picolisp*'.  If there is a process already running in 
        `*picolisp*', switch to that buffer.  With argument, allows 
        you to edit the command line (default is value of 
        `picolisp-program-name').  Runs the hook 
        `inferior-picolisp-mode-hook' (after the `comint-mode-hook' is 
        run).  (Type C-h m in the process buffer for a list of 
        commands.) 

    The fact that one can add a prefix arg to it to specify the full 
    path to the `pil` executable, and that such a specification will 
    be automatically remembered, isn't mentioned. 

      TJ> Sorry for being late to the discussion, but I'm
      TJ> not really online at the moment.

    Fair enough; life happens! i myself have a lot happening, so it's 
    important to me that my FOSS contributions aren't to no effect, or 
    become more complex to manage than i've got the time and energy 
    for. Consequently, given that the more i look at the situation 
    around the above implementations, the more contextual 
    complexity[1] i find, i feel it's best for someone else to take on 
    the work of sorting things out.

    [1] As distinct from any complexity in the code itself.

    At any rate, i've started the process of renaming my own `picolisp-mode`
    to `a-picolisp-mode`, so that it doesn't get confused with these other
    existing codebases; and in the README for my package, i'll be
    emphasising that my code is in no way connected with the PicoLisp
    support included in the PicoLisp distribution, or the modified version
    thereof available on GitHub.


    Alexis.

--- END email ---

So i think my bundle is 'better' in that it's actively maintained and actively developed by someone who's actively online, even if it doesn't (yet) have complete feature parity (although it does have functionality not available in the other two bundles: specifically, access to the PicoLisp reference documentation, either directly in Emacs or in a Web browser).

As for whether this really matters right now, well, i'd like to put a limit on the current state of confusion around these three bundles (as indicated by the above-linked thread), and ensure that there is a clear separation between my package and the other two bundles.

**Comment by purcell** [comment]
Yeah, it's tricky. The upstream maintainer has said in the exchange you posted above that patches are welcome, but you've told him that you don't want to submit them because you expect him to reject them based on past experience with other maintainers. So you *might* be making things harder than they need to be. :-) But on the other hand, I can also see your point of view.

What has worked for me in the past is to offer to take over maintainership of the original repo, ie. ask the owner for commit access.

Renaming your picolisp-mode would reduce confusion in one sense, but it would then make people confused about whether to install picolisp-mode or a-picolisp-mode. So I'm not sure if it's a net gain. :-)  Plus, it would be a pain for users if all the symbols got renamed to `a-picolisp-mode-*`.

Since you're the person most actively maintaining a `picolisp-mode.el` right now, I have no problem with leaving it in MELPA as it is.

Anyway, I'll leave the decision up to you.

**Comment by milkypostman** [comment]
So I'm confused. Let me see if I can summarize the change.

1. MELPA has been tracking the @flexibeast version of `picolisp-mode` from the beginning.
2. The @flexibeast version of `picolisp-mode` is a fork of the original version.
3. The original author hasn't been maintaining their version.
4. The PR is to rename the `picolisp-mode` package to something more specific.

At this point I don't see the point in just leaving the `picolisp-mode` recipe pointing to the @flexibeast version. 

1. It's being maintained.
2. It's already what ~70 MELPA users are using.
3. Changing the name will only cause confusion at this point.

@flexibeast can we just leave it be and you keep maintaining until the original author can step in to this discussion directly and offer their thoughts? I don't feel like there is any reason to change this unless we get specific feedback from the original author or MELPA users who feel that they have been wronged by what has transpired.

**Comment by flexibeast** [comment]
1. PicoLisp support for Emacs was created by someone other than myself. i'll refer to this person as 'U'. This support became bundled with the PicoLisp distribution, several years ago. i'll refer to this as bundle X.
2. Someone else took over maintenance of this support. i'll refer to this person as 'V'. V created [this repo](https://github.com/tj64/picolisp-mode) in which they made further additions and modifications to that codebase, which haven't been merged back into bundle X, for reasons unknown. i'll refer to this second bundle as bundle Y. No additional changes have been made to bundle Y for at least a couple of years.
3. Since the existence of PicoLisp support for Emacs is not mentioned anywhere in [the PicoLisp documentation](http://picolisp.com/wiki/?Documentation), and i could not find any existing package on MELPA providing PicoLisp support for Emacs, i created my own package from scratch, without reference to the two existing PicoLisp support bundles. And since i thought i was the first to create such support, i named it `picolisp-mode`. i'll refer to this as bundle Z.
4. In mentioning my package on the PicoLisp mailing list, it was asked if bundle Z was related to bundle X, which i had not, to that point, been aware of. My attention was also brought to the existence of bundle Y. Bundle X contains an entire file of code not included in bundle Y; bundle Y contains code changes not included in bundle X.
5. It was suggested in [this message](http://www.mail-archive.com/picolisp@software-lab.de/msg05164.html) to the PicoLisp mailing list that i rename my package, bundle Z, so as to not cause confusion with bundle X.
6. Initially i said that i would stop work on bundle Z entirely, remove it from MELPA, and instead add some of the code from bundle Z to bundle X, to give it new functionality. i also said i would review the differences between bundle X and bundle Y, and consider adding in changes in bundle Y to bundle X.
7. The creator and maintainer of PicoLisp itself, who i'll refer to as 'W', and who hasn't written any of the code for bundle X or bundle Y, said that V, the current maintainer of both bundle X and bundle Y is currently offline. However, W somehow got in contact with V and got a written response from V to what i said in step 6. The [message](https://github.com/milkypostman/melpa/issues/2514#issuecomment-74764820) i copied and pasted earlier in this thread is my response to V.
8. Given the concerns i raised in my response to V, and that it seemed like the more i looked at the situation with bundle X and bundle Y, the more untangling and work was required, i decided i would instead not take on these tasks, and simply rename and continue to maintain bundle Z, which i estimate will require substantially fewer resources of me.
9. i have, in the repo of bundle Z on my laptop, made the renaming changes, and added a sentence to the README which states "This package is not based on, nor connected with, the PicoLisp support for Emacs provided in [the PicoLisp distribution](http://software-lab.de/down.html), or the more recently [updated version of that support](https://github.com/tj64/picolisp-mode)."

Hope that makes things clearer - sorry for dropping this mess on you and @purcell. :-(

**Comment by milkypostman** [comment]
Well, at this point, I'm fine with leaving it as-is. I also can see the
community situation of wanting to have it renamed which *maybe* we want to
do sooner rather than later. But it doesn't solve the problem of the
package moving and users not knowing that it has been moved. Basically they
will have an old version that is not getting updated.

In general it sounds like the picolisp community needs to get their act
together if they really care. If it were me, I would just leave it; it's
obvious you care about the package you made and you took the time to put it
on MELPA and this is the current state of the world. It's not fair but
that's life. If the time comes that users start saying that `picolisp-mode`
on MELPA should be the *official* version then lets cross that road when we
get there. Sound good? For now I am closing this issue.

**Comment by milkypostman** [comment]
Also, :+1: thanks for taking the time to write up the explanation and give us all the details.

**Comment by purcell** [comment]
:+1:

**Comment by flexibeast** [comment]
@milkypostman, @purcell:

Thank you both for taking the time to deal with this! Yes, that sounds fine. :-) i'll revert the name-changing commits in my local repo, but push changes to the README.md summarising the situation.

Thanks again!
