### ISSUE TITLE
Erlang mode stable release

### ISSUE THREAD

**Issue by nlamirault** [milkypostman/melpa#2553]
hi,
there is no stable version for erlang mode in MelpaStable. Why ?
It seems there is some tags into the repository [1]

[1] : https://github.com/erlang/otp/tags

**Comment by purcell** [comment]
The reason is that we don't recognise those as version tags. We look for `1.1`, `r1.1`, `v.1.1` etc.

**Comment by purcell** [comment]
Solution might be to allow recipes to specify a version tag pattern.

**Comment by nlamirault** [comment]
Yes !

**Comment by milkypostman** [comment]
pull requests welcome.

**Comment by dunn** [comment]
I'm going to submit something like this to Emacs, which should make `version-to-list` parse the Erlang versions correctly: https://github.com/dunn/emacs/commit/818c5e2584cd6f41da8580b647c37206268aac8a

Are there any other troublesome version-strings that I should try to handle at the same time?

**Comment by purcell** [comment]
Nope, not that I can think of. Great that you've added tests too!

**Comment by dunn** [comment]
Unfortunately they're not on board with that idea: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22046#26

So I guess it'll have to be done by specifying a version pattern in the recipe, like you originally suggested.  Or at least a regular expression to clean the tag before sending it through `version-to-list`.
