### ISSUE TITLE
alert depends on gntp 0.1 on melpa stable, but gntp is not on stable.

### ISSUE THREAD

**Issue by ruiyang** [milkypostman/melpa#2561]
if using only stable melpa, you will not be able to install alert.

**Comment by purcell** [comment]
This is because @tekai has not added any version tags to the `gntp` repository. Hey @tekai, would you mind tagging the code there?

**Comment by tekai** [comment]
as in tag it in git with "v0.1" ?

**Comment by purcell** [comment]
Yes, exactly. :-)

**Comment by tekai** [comment]
that should be it then

**Comment by purcell** [comment]
Yay, thanks!

**Comment by myuhe** [comment]
:+1:
