### ISSUE TITLE
Which branch are packages build from

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2569]
Which branch is used by default when building packages from Github repositories? The `master` or the branch `HEAD` points at?

**Comment by purcell** [comment]
The default branch for the repository is used, usually - but not always - `master`.

**Comment by tarsius** [comment]
I believe Github's "default branch" is exposed to Git as `HEAD`. And those default to `master`.

So if I understood this right, if I want to change the default branch on Github to, let's say `next`, but keep building the Melpa package from `master`, then I have to explicitly set `:branch` in the recipe.

**Comment by milkypostman** [comment]
Yes this is correct. If you look into package-build.el we don't hardcode
*master*, rather there is a way to parse the default branch from the remote
repo info. This was done a *long* time ago---to support technomancy's
starter-kit-v2---so I don't remember all the details.
