### ISSUE TITLE
Link to Emacs 23 package.el is Broken.

### ISSUE THREAD

**Issue by haziz** [milkypostman/melpa#2580]
The link (on the "main" Melpa site) to the compatible version of package.el for Emacs 23 users is broken. Not all package.el versions seem to allow addition of Melpa as a package repository.

**Comment by purcell** [comment]
The link on [the MELPA getting started page](http://melpa.org/#/getting-started) points [here](http://repo.or.cz/w/emacs.git/blob_plain/ba08b24186711eaeb3748f3d1f23e2c2d9ed0d09:/lisp/emacs-lisp/package.el), which isn't broken. Please can you tell me how to find the broken link you're referring to?

**Comment by haziz** [comment]
This link is broken:

http://repo.or.cz/w/emacs.git/blob_plain/ba08b24186711eaeb3748f3d1f23e2c2d9ed0d09:/lisp/emacs-lisp/package.el
 
It is the link that this page 

http://melpa.org/#/getting-started

Links to as a package.el file suitable for Emacs v23.

**Comment by purcell** [comment]
The link isn't broken for me. Do you perhaps have a network routing problem?

**Comment by haziz** [comment]
Seems to have been a firewall/proxy issue for me. Sorry. 

BTW, an extremely basic question. How do I set the path to that package.el file once downloaded?

Thanks.

**Comment by purcell** [comment]
Just put it in a directory on your elisp `load-path`: use `C-h v load-path` to see what that's currently set to.

Alternatively, just explicitly add the download directory to `load-path` like this:

```el
(push "/directory/of/file/" load-path)
```

**Comment by haziz** [comment]
Thanks.
