### ISSUE TITLE
package-build.el fail in localised session

### ISSUE THREAD

**Issue by bricewge** [milkypostman/melpa#2581]
Trying to solve quelpa/quelpa#65 has bring me here.

When using some functions of `package-build.el` on a localized session such as `pb/git-repo` the search fail because the regex is in english. For example `Fetch URL:` is translated to `URL de rapatriement :` which give this error: `Search failed: "Fetch URL: \\(.*\\)"' 

A dirty fix was to add to my init.el `(setenv "LC_ALL" "C")`.

**Comment by purcell** [comment]
Makes sense. We can probably try to run all commands using `env LC_ALL=C ...`.

**Comment by purcell** [comment]
Done in 383cd57 -- let me know if that helps.

**Comment by bricewge** [comment]
Thanks! You solved it.
