### ISSUE TITLE
gitorious pulls failing.

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#2587]
The following packages are failing to build:

```
evil
notmuch-unread
paradox
pov-mode
python-mode
tempbuf
```

They are all on gitorious which is apparently shutting down since they [got acquired by Gitorious](https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/).

Not sure they *should* be down but even my manual clones fail.

**Comment by purcell** [comment]
Hmm. I can clone `evil` here, at least:

```
% git clone https://gitorious.org/evil/evil.git
Cloning into 'evil'...
remote: Counting objects: 6147, done.
remote: Compressing objects: 100% (5331/5331), done.
remote: Total 6147 (delta 2137), reused 4665 (delta 812)
Receiving objects: 100% (6147/6147), 13.08 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (2137/2137), done.
Checking connectivity... done.
```

**Comment by milkypostman** [comment]
hrm, i was using `git clone git://gitorious.org/evil/evil.git` and that doesn't work. it's what is on their website. think things may have changed then.

**Comment by purcell** [comment]
Great!
