### ISSUE TITLE
w3m is compiling unrelated files returning errors

### ISSUE THREAD

**Issue by thierryvolpiatto** [milkypostman/melpa#2592]
namely "octet.el" (needed for Xemacs but not Emacs)  "mew-w3m.el" (probably this can be provide as a separate package) and "w3m-xmas.el" (only Xemacs also).

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Closed #2592 via deb235d.

Thanks, seems mime-w3m.el is also unneeded for Emacs.
The list of files to be byte-compiled is available with
(w3mhack-module-list) from w3mhack.el.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Thanks - updated in ce1dc68.

**Comment by egh** [comment]
I need `mime-w3m`, it is used by wanderlust. If there is no reason to exclude it, could you bring it back? Thank you for all your hard work on MELPA.

**Comment by purcell** [comment]
@egh Done - sorry about that.

**Comment by egh** [comment]
Thanks, @purcell ! Much appreciated as usual.
