### ISSUE TITLE
Recipe for matlab-emacs does not install all the required files.

### ISSUE THREAD

**Issue by se4u** [milkypostman/melpa#2601]
The recipe for the package matlab-emacs fetches only the .el files in the top level folder. 
I am not sure whether it is because it does not fetch the folders "toolbox" and "templates" or whether it discards them. Nevertheless it does make the package on Melpa a bit misleading since one ends up wasting time on the package installed through MELPA which does not work but does not give any errors.

**Comment by purcell** [comment]
It's easy enough for us to include those folders in the package, but if they require any build steps via the Makefiles, that would still need to be done after downloading.

The recipe was contributed by @chachi -- does this problem not affect you, Chris?

**Comment by chachi** [comment]
Sorry, I haven't used this in a while, as I no longer have a MATLAB installation to work with.

**Comment by purcell** [comment]
It looks like there have been a couple of thousand downloads. I wonder if it works for anyone... Maybe we should just remove the package.

(P.S. Not sure why github showed your name as "Chris Barrett" in the @-dropdown. Sorry!)

**Comment by se4u** [comment]
There is a separate compilation step which requires knowledge  of the path
of cedet.el

Since the elisp files by themselves (without the build step) give partial
benefits like syntax highlighting but dont support other features like
static lint, cedet integration, so I am also  not sure about removing the
package entirely.

**Comment by yangj1e** [comment]
I think the path of CEDET is required only when you are using an alternate version of CEDET.
The "toolbox" and "templates" folders are necessary. Not sure whether additional build step is needed as I have not build it.

**Comment by rmgarnett** [comment]
There are three important helper .m files (emacsinit.m, opentoline.m, and emacsdocomplete.m) in the toolbox/ directory that need to be in MATLAB's path for things like tab completion to work correctly when running MATLAB in emacs via matlab-shell.  Fetching these at installation would be great.  I currently have matlab-mode installed via MELPA, and everything works fine except that I have to fetch the files in toolbox/ separately.  The templates/ directory appears to contain a SREcode template (srecode-matlab.srt).

Both makefiles in these directories simply copy the relevant files (the three .m files and the .srt file, respectively) to toolbox/ and templates/ directories in the target directory.

I'd hate to see this package removed from MELPA; I think the only thing to get full operation is to additionally fetch these four files.

**Comment by milkypostman** [comment]
roman. are the files available in the repo? either you could update the
recipe for us or you could list the files that are needed and we could
update the recipe to include these files. our build will do the copying as
we don't allow makefiles to run on our build servers.
