### ISSUE TITLE
apel package fails to install with cl-subseq throwing an error

### ISSUE THREAD

**Issue by zhenya1007** [milkypostman/melpa#2606]
Hi, there,

The copy of apel-pkg.el from git://github.com/wanderlust/apel.git (branch apel-wl) looks like this:
```
(define-package "apel" "10.8"
  "APEL (A Portable Emacs Library) provides support for portable Emacs Lisp programs")
```
When processing this definition, package-build.el (from git repo version  b7f62ac156) was throwing
in `pb/get-pkg-file-info` when trying to evaluate 
```
(let* (... (rest-plist (cl-subseq pkgfile-info 4)) ...) ...)
```
I got the appel package to install using the big hammer of `condition-case`, like so:
```
@@ -749,7 +750,9 @@ Optionally PRETTY-PRINT the data."
       (if (eq 'define-package (car package-def))
           (let* ((pkgfile-info (cdr package-def))
                  (descr (nth 2 pkgfile-info))
-                 (rest-plist (cl-subseq pkgfile-info 4))
+                 (rest-plist (condition-case nil
+                                (cl-subseq pkgfile-info 4)
+                              (error nil)))
                  (extras (let (alist)
                            (while rest-plist
                              (unless (memq (car rest-plist) '(:kind :archive))
```
However, I don't know enough about proper format for *-pkg.el to know if the `define-package` in apel is actually reasonable (in which case I would ask you to consider adding something like the code above to package-build), or if that `define-package` is malformed (in which case I'll go file an issue on apel).

What is your take on this?  Thanks in advance!

P.S. A quick look at [the Elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html) suggests that one can give as few as two arguments to `define-package`, but I am sure you have much more experience with this...

**Comment by milkypostman** [comment]
This is something I have seen crop up in other packages as well. Seems that `cl-subseq` got strict.

Think this should work fine. I tested it now on my box and it builds the `apel` package.

Thanks for tracking it down. It made it a **lot**easier to fix to know where it was happening---as opposed to "hey I can't build apel package" :)
