### ISSUE TITLE
Rename of package purpose to window-purpose

### ISSUE THREAD

**Issue by bmag** [milkypostman/melpa#2617]
Hi,
@jasonm23 [suggested](https://github.com/bmag/emacs-purpose/issues/39), and after consideration I agree with him, that I should rename the package "purpose" to "window-purpose". Note that I don't want to change the URL, but only the package's name.

I've found similar issues in  #956, #986 and #2514, and it seems to me that the best way to do it is in two steps. First step will rename the old files and all the symbols, add a purpose.el file with warnings and aliases for backward-compatibilty, and create a recipe for the new name. Second step will remove the old recipe and the purpose.el file. I think a month between the two steps will be enough for users to move to the new name.

Before I make these changes, I want to be sure that it's OK with you to rename the package. Do you think the renaming process should be done differently?

Thanks,
Bar

---

Detailed plan:

1. Rename files to start with "window-purpose" instead of "purpose"

2. Rename symbols to start with "wp/" instead of "purpose-" (I wanted "wp-", but that's already used by [wp-mode](https://github.com/danlamanna/wp-mode))

3. Add file "purpose.el" which:
   - requires the new files, via `(require 'window-purpose nil t)`
   - warns the user about the package's new name
   - defines obsolete functions and variables with the old names. This should help existing users fix their configs and get used to the new symbol names.

4. Changes to recipes:
  - purpose recipe: keep as is for a month, so it installs both purpose.el and the new files.
  - window-purpose recipe: new recipe, fetches only the "^window-purpose.*el$" files.

5. In another month: remove purpose recipe and purpose.el

**Comment by jasonm23** [comment]
:+1:

**Comment by purcell** [comment]
This is fine with me. Let's just do the renaming in the most straightforward way: rename the `.el` file and adjust the recipe accordingly. If you do the former, I can take care of the latter promptly. The recipe will get an `:old-names` key so that the old MELPA package page will get redirected, and the downloads totaled appropriately.

We don't encourage "staged" plans to help users through a renaming, except in the case of spectacularly popular packages.

**Comment by bmag** [comment]
I have a few .el files. Should I rename all of them, or just the main one (purpose.el)?

**Comment by bmag** [comment]
OK, I've renamed the files.

**Comment by purcell** [comment]
Cool, done on this side too. :-)

**Comment by bmag** [comment]
Thanks :-)

**Comment by jasonm23** [comment]
Nice work gents @bmag @purcell
