### ISSUE TITLE
Use specific fork of some package

### ISSUE THREAD

**Issue by kostafey** [milkypostman/melpa#2638]
Coud you tell me please is there any way to use some specific fork of a package?

E.g. there is [popup-el](https://github.com/auto-complete/popup-el) package and I want to use my own frok. Is there any solutions to do it via package engine?

**Comment by milkypostman** [comment]
sorry, how do you mean? like you want to build your version locally or have
MELPA build it?

**Comment by purcell** [comment]
`package.el` will always download the original version of the fork, but you should be able to put a local clone of your fork earlier in `load-path` than the installed packages, and then Emacs will load that instead.

**Comment by kostafey** [comment]
> sorry, how do you mean? like you want to build your version locally or have
MELPA build it?

@milkypostman, it does not mean. It seems, the only way is to build it via MELPA.

> but you should be able to put a local clone of your fork earlier in load-path than the installed packages, and then Emacs will load that instead.

@purcell, I'm searching the way to make dependency from fork with auto install and update possibility of it, like any odinary package. Is there no way to do that without adding a fork as new package? I would not like to do that for obvious reasons :).

**Comment by purcell** [comment]
If it's a single-file package, you can just install it directly with `package-install-file`...

**Comment by kostafey** [comment]
Yes, but file should be downloaded and located in suitable place. It seems, the only way is to use `el-get` or ordinary manual installation.
Thank you for advice.

**Comment by Silex** [comment]
@kostafey: https://github.com/quelpa/quelpa can make whatever you want available for package.el installation

**Comment by kostafey** [comment]
@Silex, thank you! Quelpa looks good.
