### ISSUE TITLE
Providing a description for the ESS package

### ISSUE THREAD

**Issue by sje30** [milkypostman/melpa#2655]
Hi,

Apologies in advance if this is a simple question.  I'm one of the devels of ESS (https://github.com/emacs-ess/ESS) which is on melpa.   We currently don't have a file called lisp/ess-pkg.el but I can add one if you suggest what I can add.  In particular what should the version number be?

**Comment by purcell** [comment]
Great, thanks. You can just use `0` for the version number: we'll fill it in for you.

**Comment by sje30** [comment]
Thanks!  Is this edit sufficient?

https://github.com/emacs-ess/ESS/commit/2fa5d38030f3e76b2ea1c2da73ec04ae9e819612

**Comment by sje30** [comment]
Hmm... should the version be "0" as a string?

**Comment by purcell** [comment]
Yes, actually I think it should be a string. Sorry for any confusion.

**Comment by sje30** [comment]
Thanks Steve; but our package is still listed without a description; it is listed on melpa as:

    ess 20150405.1150 No description available.

How do I get the description in?

**Comment by purcell** [comment]
Ah, that's interesting -- I think this is a fault on our side, due to the fact that the `-pkg.el` file isn't in the root directory of your repo. We'll need to fix things up in our code. I'll take a look at that as soon as I get chance. Your file is fine -- thanks for your patience!

**Comment by milkypostman** [comment]
hold up @purcell i think i know the problem. testing.

I'll fix this up either way.

**Comment by milkypostman** [comment]
@sje30 @purcell so the problem is that putting a `-pkg.el` file in a subdirectory doesn't make sense to the package system I don't think.

**Comment by milkypostman** [comment]
and `package.el` just generates the `-pkg.el` file if it doesn't exist. so I will update the recipe to properly copy the file to the correct location.

**Comment by sje30** [comment]
Thank you Steve and Donald.  I see now that you have fixed it.

**Comment by purcell** [comment]
Separately, I should point out that distributing an `-autoloads.el` file is generally undesirable and unnecessary: the `update-directory-autoloads` function can generate such a file from appropriate `;;;###autoload` markers elsewhere in the source code, so you can call that from a build process when constructing a tarball, and `package.el` automatically does this at package installation time.

**Comment by sje30** [comment]
Thanks.  Our autoloading is a bit clunky and not to be relied on
unfortunately.  e.g. I think whenever a bit of ESS is needed, it should
load ess-site.el which sets everything up.

S
