### ISSUE TITLE
Instructions for Installing MELPA May Have Undesirable Side-Effects

### ISSUE THREAD

**Issue by mobatemc** [milkypostman/melpa#2674]
On Windows 7, with Emacs 24.4.1 installed using Ron Goulet's installer, I installed MELPA following the instructions at http://melpa.org/#/getting-started. Apparently, a side effect of running 'package-initialize' in my Emacs initialization file was to push a path to the built-in AUCTeX package onto the load-path, thereby shadowing a more recent AUCTeX installed in my .emacs.d and causing confusing errors such as "Error running timer `font-latex-jit-lock-force-redisplay': (wrong-number-of-arguments (2 . 2) 3)".

An approach to installing MELPA that avoids this problem is to customize the variable `package-archives' using the custom system.

**Comment by purcell** [comment]
> An approach to installing MELPA that avoids this problem is to customize the variable `package-archives' using the custom system.

That only works if the custom system controls package initialisation, which isn't the case in many of the popular configuration bundles. It's not something we could recommend as a standard approach.

It's not unexpected that `package-initialize` would modify `load-path`, but I can't comment on this particular problem without more info... it's possible auctex does something funky, or that there's something else in your config which is affecting the load path or initialisation order.

**Comment by mobatemc** [comment]
Then for Vincent (not Ron) Goulet's Emacs installer version emacs-24.4-modified-2, using the custom system seems a better approach to installing the MELPA repository than the recommended approach, with your caveat that you believe this requires that "the custom system controls package initialization". (How do determine this last condition?)

BTW, I killed my initializations, installed AUCTeX 11.88.4, and started Emacs with and without "package-initialize" as my only local action. With "package-initialize", the old AUCTeX path was moved ahead of the new AUCTeX path. Without "package-initialize" or with "(package-initialize t)" to suppress activating the packages, the path orders are not swapped. Only the new AUCTeX package is selected by "package-initialize", so only its initializer is run. So it does appear that AUCTeX initialization does something funky to the load path.

**Comment by purcell** [comment]
> with your caveat that you believe this requires that "the custom system controls package initialization". (How do determine this last condition?)

Not sure if there's a 100% reliable method to do that for all reasonable Emacs & package.el versions. Essentially, the user can either call `(package-initialize)` or leave Emacs to do that automatically. Generally if people are setting up package archives in their Emacs init code, it's so that subsequent init code can depend on packages being installed and initialized, ie. the common pattern is

```el
(require 'package)
...
(add-to-list 'package-archives '(...))
(package-initialize)
...

(require 'some-package)
(some-package-whatever-mode t)
```

**Comment by purcell** [comment]
Closing as this seems due to the auctex quirk rather than any fault with package.el or MELPA.
