### ISSUE TITLE
Reordering dependencies causes installation to fail on 24.3

### ISSUE THREAD

**Issue by cpitclaudel** [milkypostman/melpa#2744]
Some users of my package `company-coq` on emacs 24.3 privately reported issues with installation, related to the order in which dependencies are installed. I can partly reproduce them:

If I use 

```elisp
(define-package
  "company-coq"
  "0.3"
  "Company-mode backend for Proof General's coq-mode"
  '((company-math "0")
    (company "0.8.12")
    (yasnippet "0.9.0.1")
    (cl-lib "0.5")))
```

Then things install properly. If I use

```elisp
(define-package
  "company-coq"
  "0.3"
  "Company-mode backend for Proof General's coq-mode"
  '((company "0.8.12")
    (company-math "0")
    (yasnippet "0.9.0.1")
    (cl-lib "0.5")))
```

then installation fails:

```
... yasnippet gets compiled ...
company-math.el:35:1:Error: Cannot open load file: company
... company gets compiled ...
company-coq.el:61:1:Error: Cannot open load file: company-math
```

and 

```
Warning (emacs): Unable to activate package `company-math'.
Required package `company-0.8.0' is unavailable
```

Is it expected that reordering package dependencies should fix this problem? Or is there a more reliable fix?

**Comment by cpitclaudel** [comment]
Additional notes: `company-math` registers a dependency on `company-0.8.0`; `company-coq` registers a dependency on `company-0.8.12`.

**Comment by purcell** [comment]
It is *not* expected that reordering dependencies would affect the installation results. If the problem doesn't happen in newer Emacs versions, then you can assume this is an Emacs bug which has since been fixed. I'm not aware of a more reliable workaround, unfortunately.

**Comment by cpitclaudel** [comment]
Thanks!
