### ISSUE TITLE
Denote wiki packages with a keyword

### ISSUE THREAD

**Issue by Malabarba** [milkypostman/melpa#2773]
As per twitter discussion, it would be nice if Melpa denoted in `archive-contents` which packages are from the wiki. The most appropriate way would probably be something like a `(:source 'wiki)` keyword.

With this, I could add some functionality to indicate and (optionally) hide wiki packages in Paradox.

(On an somewhat related and less important note, Melpa could also expose information like `((:source github) (:repo "username/reponame"))`, but the resulting increase in size of the archive-contents file might be undesirable).

**Comment by milkypostman** [comment]
hrm, we used to append [wiki] to the package name but guess that got
removed....

**Comment by purcell** [comment]
Yes, there were various reasons for removing the `[source]` tags, not least of which was that the info isn't really helpful to most users.

We can certainly add a `:source` keyword or similar to `archive-contents`, though the way the data for each entry is currently handled makes that a bit more fiddly than it should be.

**Comment by Malabarba** [comment]
Well, fwiw, I'm writing up a solution using the recipes.json file. So feel free to close this issue.
