### ISSUE TITLE
http://melpa.org/ says "Last build ended: 18 hours ago", Is this normal?

### ISSUE THREAD

**Issue by xuchunyang** [milkypostman/melpa#2788]
I thought it should rebuild about every 2 hours.

**Comment by purcell** [comment]
Thanks for the notification. Disk is full. Will investigate.

**Comment by purcell** [comment]
Should be running again now. @milkypostman - I cleared out tempfiles, but there's only about 1.5GB free. Haven't investigated what's using the space.

**Comment by milkypostman** [comment]
Ok it's probably that our packages are growing and each repo adds up.

**Comment by Silex** [comment]
A quick `du -hs *` around specific directories should quickly answer that no?

**Comment by purcell** [comment]
@milkypostman I made a change to prevent so many temp dirs being left around, but yes, the sheer weight of the working directories is probably a prime issue. I wonder to what extent we could copy only partial history when cloning upstream repos.

**Comment by milkypostman** [comment]
yeah depth 1 or whatever on history would probably work. also we may be
pulling down all remote branches...

**Comment by purcell** [comment]
> yeah depth 1 or whatever on history would probably work.

As long as we can find the last-commit times for all files, even if those commits were a long time ago...

> also we may be pulling down all remote branches...

Probably only a small win compared to pruning history.

**Comment by milkypostman** [comment]
yeah, so there is like 8-9 gigs for the repos, and 1 gig for old log files.
then that's about all there is to the server. I'll look into getting
lighter checkouts in the future.

probably if we deleted all repos and pulled down fresh we'd see a reduction
in size too.

**Comment by purcell** [comment]
Yeah, we could also periodically run `git gc` in every subdir of `working` which has a `.git`.

**Comment by milkypostman** [comment]
So complex! ;)

**Comment by purcell** [comment]
I do exactly on another server (which shall remain nameless), because I'm a space miser.
