### ISSUE TITLE
Don't exclude explicitely included `.gitignore`

### ISSUE THREAD

**Issue by AdrieanKhisbe** [milkypostman/melpa#2808]
This is a follow up on #2772:

@purcell pointed out it was coming `pb/create-tar` where w various files internal to version control systems (e.g. _darcs, .svn, .git*), where excluded. remnant of  the early days of MELPA in late 2011.

*Reminder:* The goal of the  cask-package-toolset package is to help setup a CI environment for developed package, hence the `.gitignore`, `.travis.yml` and `Makefile` that need to be included :)

**Comment by AdrieanKhisbe** [comment]
Hey  @milkypostman and all :)

I can do the modification on https://github.com/milkypostman/melpa/blob/master/package-build.el#L665-L682 if you want, but I prefer to have a *'go'* before to do it :)

and a *how* too ^^:
I would tend to just remove all the options given to `find` as @purcell suggested in #2772.

**Comment by purcell** [comment]
> I would tend to just remove all the options given to find as @purcell suggested in #2772.

I think I remember looking at whether that would work, and decided that was too simple to be a full solution.  The main problem I can think of right now is that when a package contains a git submodule `foo` and the recipe includes `foo`, then the tar files would contain the `foo/.git` directory.  Looking at it again now, I think a possible solution might be to change the `.git*` exclude pattern to simply `.git`.

**Comment by purcell** [comment]
I've committed that change in 6425fa7 -- your package will get updated (with the same timestamp) during the next package build cycle. You can also try building it locally now with `C-c C-c` to see if you get the desired result.

**Comment by purcell** [comment]
And if it does work, please go ahead and close the issue in case I forget. :-)

**Comment by AdrieanKhisbe** [comment]
Thanks @purcell, Gonna test right now :)

**Comment by AdrieanKhisbe** [comment]
It's working!! :)
Big thanks purcell!

**Comment by purcell** [comment]
Great, thanks for your help.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)
