### ISSUE TITLE
Installation - Package not found in in MELPA

### ISSUE THREAD

**Issue by rogeliozarate** [milkypostman/melpa#2819]
Hi,
I attempted to install the package org-pomodoro via MELPA, using GNU Emacs 25.0.50.1 in OS X Mavericks:
```M-x package install RET org-pomodoro```
, receiving the following message:
```http://melpa.milkbox.net/packages/org-pomodoro-20150331.1023.tar: Not found```
Is this related to MELPA or the package itself?
Is there a workaround?

**Comment by milkypostman** [comment]
You need to update the package listing. Can't remember the command offhand.
But that version is out of date so it suggests your index is out of date.

**Comment by rogeliozarate** [comment]
This will do it:
M-x package-refresh-contents
Thank you,
