### ISSUE TITLE
Question about org related packages and org-loaddefs.el

### ISSUE THREAD

**Issue by syl20bnr** [milkypostman/melpa#2826]
I installed `ox-gfm` and had issue with void functions errors for some org functions. If I remove the file `org-loaddefs.el` from the install directory of `ox-gfm` the issue goes away. Maybe this file shadows the `org-loaddefs.el` of org itself.

Is it expected to generate this file ?

**Comment by syl20bnr** [comment]
I also asked the question to the package author. He is not the one who put the package in MELPA so he cannot help on this. https://github.com/larstvei/ox-gfm/issues/4

**Comment by milkypostman** [comment]
i have no idea about this. org is a huge ball of trouble.

**Comment by purcell** [comment]
Problem is with the upstream code overriding `generated-autoload-file`, which subverts `package.el`'s own autoload generation. Hopefully the author will fix it up. Will close this issue.
