### ISSUE TITLE
Melpa-Stable and shared repositories

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#2836]
What happens when two libraries are maintained in the same repository but are distributed as separate packages on Melpa and Melpa-Stable? I suspect that pushing a new tag bumps the version of both packages on Melpa-Stable.

I am aware of one such case - but it's a special case, so I cannot really draw any conclusions from it.

```lisp
(magit :fetcher github
       :repo "magit/magit"
       :branch "master"
       :files ("magit.el" ...))
```

```lisp
(with-editor :fetcher github
             :repo "magit/magit"
             :branch "next"
             :files ("with-editor.el"))
```

Both recipes set `:branch`, so I am surprised to find `magit-1.4.1` on Melpa-Stable but not any version of `with-editor`. Maybe the use of the `:branch` keyword prevents new releases from appearing on Melpa-Stable? In that case `magit-1.4.1` probably exists because the respective tag was pushed before the `:branch` keyword was added to the recipe (provided that actually is the case, I doubt it is). Or maybe the value of `:branch` makes a difference.

Anyway the current version of magit should be `1.4.1` while with-editor `1.0.0` is about to be released. Maybe you could extend how the latest tag is determined, i.e. if there are any tags of the form `PACKAGENAME-VERSION` then consider only those, and only if there are no such tags consider the regular `VERSION` tags.

**Comment by milkypostman** [comment]
Oh yes. We have a bug somewhere. It's possible we could update the tagging
mechanism but I am a bit weary of this. Actually. I think we were thinking
of adding a way to specify a regex for a package. With this you could do as
you are saying. You would just write a custom regex for each package to
determine the stable version.

But man. Stable is not even on my radar for things to work on. It's one of
those things I realize people like but I don't use or understand
personally.

I guess we could add this as a todo.

**Comment by tarsius** [comment]
> It's possible we could update the tagging mechanism but I am a bit weary of this. Actually. I think we were thinking of adding a way to specify a regex for a package.

Now that you mention it, I think I have over~~seen~~"heard" that conversation.

> It's one of those things I realize people like but I don't use or understand personally.

I completely understand, there's absolutely no rush from my side. It just means that `magit-popup-1.0.0` won't appear on Melpa-Stable now. I am considering to keep the versions of packages that share a repository in sync anyway. Of course that has the downside that when I release `magit-n+1` then `with-editor-n+1` would also be released, even though it might not have a single additional commit compared to `with-editor-n`

> Oh yes. We have a bug somewhere.

That's a bit more of a problem. Once I release `magit-2.1.0` `with-editor` should also be available from Melpa-Stable, it's a mandatory dependency. So what do you think where the bug lies? Is there a good change that dropping the `:branch` from both recipes would prevent it from kicking in? I am going to do that anyway before I release `2.1.0` (as we discussed in #2640 and #2641).

Can you think of another pair of packages sharing a repository?

**Comment by purcell** [comment]
From what I see of the code, `:branch` should never get in the way of the tags working properly.

> Of course that has the downside that when I release magit-n+1 then with-editor-n+1 would also be released, even though it might not have a single additional commit compared to with-editor-n

Indeed.

> So what do you think where the bug lies? Is there a good change that dropping the :branch from both recipes would prevent it from kicking in? I am going to do that anyway before I release 2.1.0 (as we discussed in #2640 and #2641).

I'm a bit mystified by this. Don't have time to dig into this right now, but it should be possible to test this locally by setting `package-build-stable` to `t` and then hitting `C-c C-c` in the `with-editor` recipe buffer.

> Can you think of another pair of packages sharing a repository?

I know there are a few, but can't remember what they are off-hand.

-Steve

**Comment by milkypostman** [comment]
with-editor was not released with version 1.4.1. Or at least it's not tagged with it.

**Comment by purcell** [comment]
Indeed.

**Comment by tarsius** [comment]
How did I miss this crucial little detail. Sorry for the noise.

I assume you already have another open issue about the tag-regexp thing.
