### ISSUE TITLE
Duplicate entries in load-path.

### ISSUE THREAD

**Issue by spelufo** [milkypostman/melpa#2856]
The issue is described [here](https://emacs.stackexchange.com/questions/13119/why-load-path-duplicates/13129).

I don't know what the issue is, and why changing the order of the package-archives fixes it, but I guess this could be fixed by ensuring you use the same convention (with or without trailing whitespace) for load paths. Or check for path equality instead of string equality to instert paths into the load path. If this is not your code then the only things that needs to be done is fix your getting started page to recommend a better method.

**Comment by purcell** [comment]
It does seem odd that the `APPEND` argument would cause problems, but I've applied this fix nonetheless.
