### ISSUE TITLE
mode-line-in-header package missing

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#2868]
@EricCrosson what happened to `mode-line-in-header`? Is @larstvei the new maintainer?

**Comment by larstvei** [comment]
Hi!

I'm not the maintainer, just made a small addition!

**Comment by EricCrosson** [comment]
Aw shoot :( I deleted the repo. I had originally made this as a step towards what Olivetti mode does, so when I integrated Olivetti mode I broke down all the packages I hobbled together to make my own version. 

With no stars I figured it wasn't being used.. Forgot I already had somebody submit a patch. 

I have a local copy at home I could restore the package if absolutely necessary. My intent was to delete it though

**Comment by milkypostman** [comment]
thanks for sending this. In the future you can just let me know and I don't mind making the commit :)
