### ISSUE TITLE
Disk full

### ISSUE THREAD

**Issue by purcell** [milkypostman/melpa#2886]
100% of 20GB on / is currently used:

~melpa is 9.7GB:
- ~melpa/melpa/working is 7GB
- ~melpa/log is 1.1GB

/tmp is ~300MB
/var is 1.8GB
- /var/log is 1.1GB.

**Comment by purcell** [comment]
I'm `git-gc`-ing all the working dirs as a first step. Next plan is to use git's ["sparse-checkout" support](http://jasonkarns.com/blog/subdirectory-checkouts-with-git-sparse-checkout/) to avoid cloning entire huge repos of which we only need a single small subdir (e.g. `erlang`).

**Comment by purcell** [comment]
On second thoughts, I'm not sure `sparse-checkout` would help much -- it will reduce the space taken up by working copies, but the entire repo history will still be there in the packed git objects, so where a repo's history is much bigger than a working copy the benefit will be minimal.

**Comment by milkypostman** [comment]
sometimes it's better to just delete all the working directories. that
clears things. up

**Comment by milkypostman** [comment]
I wonder if we need to start pruning packages i they don't have a lot of
downloads or appear to be fairly old?

**Comment by purcell** [comment]
Or perhaps upgrade the VPS.

I need to look at the size of the working dirs versus the `.git/objects` dirs to see if `sparse-checkout` might be good. I suspect the prime offenders are the big language repos which have a little `$lang-mode.el` buried deep inside them.

**Comment by purcell** [comment]
Back to 2.6GB free after running `git-gc` in all the working dirs. I suspect that might result in more efficient packing than simply deleting the working dirs and allowing them to get recreated.

**Comment by milkypostman** [comment]
so, i found that the linux headers were piling up so I apt-get autoremove
and it removed those. that's like an extra gig that I could remove.

**Comment by milkypostman** [comment]
7.2G free now. deleted working and it's only 4GB now. I don't recall what it was after the GC.

**Comment by purcell** [comment]
Super. That should keep us going for a while.
