### ISSUE TITLE
Git lens not built

### ISSUE THREAD

**Issue by pidu** [milkypostman/melpa#2891]
Git lens was accepted into melpa but does not seem to be part of the build?

**Comment by willghatch** [comment]
My recently added package isn't building either.  I believe #2886 should probably not have been closed.

Melpa people, do you need a bigger server?  I and others would probably be happy to chip in monthly server costs if that helps.

**Comment by milkypostman** [comment]
I'll have a look in the next couple hours.

**Comment by milkypostman** [comment]
all is fine. ubuntu gets some cruft over time with linux-headers and it was
adding up. there was also come general git clutter. will keep a closer eye
on it. mostly it just works so i will add some monitoring for disk space
and determine if we *really* need more server space.

**Comment by pidu** [comment]
Well it seems to work again, closing this then.
