### ISSUE TITLE
git-commit-training-wheels-mode fails to install

### ISSUE THREAD

**Issue by moonlite** [milkypostman/melpa#2894]
I get this when I try to install `git-commit-training-wheels-mode`:

```
Install package `git-commit-training-wheels-mode-20131121.544'? (y or n) y
package-compute-transaction: Package `git-commit-mode-0.14.0' is unavailable
```

My pretty uninformed guess is that it should depend on `git-commit` instead of `git-commit-mode` but not sure.

**Comment by purcell** [comment]
This would be an issue for the upstream author, presumably @tarsius, who looks after `magit` etc. `magit` just saw a big breaking release today, and the changes have only just hit MELPA: it's possible that the training wheels mode will be considered defunct.

**Comment by tarsius** [comment]
I don't think this package is really all that useful. But it could be adapted. See https://github.com/yasuyk/git-commit-training-wheels-mode/issues/1.
