### ISSUE TITLE
magit-svn package mismatch with upstream

### ISSUE THREAD

**Issue by randymorris** [milkypostman/melpa#2895]
The [melpa package](http://melpa.org/#/magit-svn) was rebuilt about four months ago, and the file included in this package lists a dependency on magit 1.3.  The [magit/magit-svn](https://github.com/magit/magit-svn/) repo was last updated 10 months ago and lists magit 2.1 as a dependency.

The author appears to have pulled it out of the magit repo and into its own repo and had filed a [pull request](https://github.com/milkypostman/melpa/pull/2608) to have the melpa package updated.  AFAICT all of that went smoothly and the package was rebuilt but the file in the package doesn't match what's in the upstream repo.

I'm not really sure what's going on here.

**Comment by purcell** [comment]
Worked fine when I built this locally. I've removed the corresponding check-out dirs on the server, so let's see what happens when the packages rebuild there.

**Comment by randymorris** [comment]
Looks like the rebuild happened and it is now showing the updated file. Unfortunately it also changed the version to an older version number so I'm guessing no one will get the update without uninstalling the package first. I'm away from my computer for the weekend so I can't really do any testing.

**Comment by milkypostman** [comment]
Yes it's really hard for us to get accurate versions when things change on
the repo. Somehow, maybe from rebase, the latest commit will have a later
date than the one before us. There is no "last change" date in got that I
have ever been able to find. We try to use the merge date when that is
possible. Normally this happens and it eventually works itself out.

**Comment by purcell** [comment]
I guess if there's a rebase before pushing to master, and there are no merges, then there's absolutely no guarantee that the head commit is the newest. Do we look at the latest date of the commits which touched a file, or the date of the last commit? If - as I suspect - it's the latter, perhaps it's possible to do the former, even if it's expensive. Seems like an edge case that I'm not particularly motivated to address tbh.

**Comment by milkypostman** [comment]
Pretty sure the code only looks for commits relevant to the specific files. At least that was my intention.

**Comment by purcell** [comment]
Yes, it does, but it could either search back through the log output for the last-mentioned commit timestamp, or for the most-recent commit timestamp. I think it does the former.

**Comment by tarsius** [comment]
Pushed https://github.com/magit/magit-svn/commit/ca6e375423d36fc6f26bb9a8729e3008123f12a4 to trigger a rebuild.
