### ISSUE TITLE
project-persist not building

### ISSUE THREAD

**Issue by rdallasgray** [milkypostman/melpa#2903]
Hi folks -- a graphene user has reported an issue with project-persist not building. I think this has been caused by an error on my part in creating a submodule declaration. I've now fixed the error, but it's still not building. The last time this happened (sorry!) I think @purcell had to clear out the working directory and force build it (see https://github.com/milkypostman/melpa/pull/2756). 

Sorry for the hassle and many thanks in advance for sorting it.

**Comment by milkypostman** [comment]
this is on stable?

**Comment by milkypostman** [comment]
well, i think it's fixed now on both. 3.2 on stable. I don't know why it was missing but it built just fine and worked for me. let us know if there are further problems.

**Comment by purcell** [comment]
I did a tweak in 954b2a3, such that the submodules will get fully re-initialised on each update. I suspect that will prevent the problem in future.

**Comment by rdallasgray** [comment]
Great, thanks guys.
