### ISSUE TITLE
404 not found when installing highlight-blocks

### ISSUE THREAD

**Issue by shigemk2** [milkypostman/melpa#2911]
### Outline

When I install highlight-blocks on MELPA, I got 404 not found page.
http://melpa.org/packages/highlight-blocks-20150626.552.el

### Environments

* Emacs 24.5.1
* Fedora 20

**Comment by milkypostman** [comment]
I am away for today.

**Comment by milkypostman** [comment]
It looks like maybe you haven't updated your package list because that is
not the latest version.

**Comment by purcell** [comment]
Yep. `M-x package-refresh-contents` and try again.

**Comment by shigemk2** [comment]
Thanks.
