### ISSUE TITLE
package-build--update-git-to-ref seems to fail

### ISSUE THREAD

**Issue by vyp** [milkypostman/melpa#2918]
Disclaimers:

1. I am new to emacs.
2. I am using quelpa, which uses package-build. Are you familiar with quelpa?

```
Fetcher: github
Source: capitaomorte/yasnippet

Updating /home/rws/.emacs.d/quelpa/build/yasnippet/
Quelpa: failed to checkout `yasnippet': `Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 git submodule foreach --recursive git submodule deinit $path)' exited with non-zero status 1: Fetching origin
HEAD is now at 197db9f Merge pull request #578 from aluaces/patch-1
Entering 'snippets'
error: pathspec 'snippets' did not match any file(s) known to git.
Did you forget to 'git add'?
Stopping at 'snippets'; script returned non-zero status.
```

This happens when updating yasnippet with the current yasnippet recipe: https://github.com/milkypostman/melpa/blob/6417dd3e9cd5eb781c7c473f29128d35c87fd587/recipes/yasnippet. I'm not sure why the `snippets` directory is not there for it, I would have thought the `foreach` would take care of that.

Can you reproduce? Also see https://github.com/milkypostman/melpa/commit/954b2a3ac6a721e63e6f5d06b75c67343777d6b1, commit that I think introduces the function, and https://github.com/quelpa/quelpa/issues/74.

**Comment by steckerhalter** [comment]
here is what seems to happen:

```cl
HEAD is now at 197db9f Merge pull request #578 from aluaces/patch-1
Entering 'snippets'
/home/user/.emacs.d/quelpa/build/yasnippet/snippets
snippets
Entering 'yasmate'
/home/user/.emacs.d/quelpa/build/yasnippet/yasmate
yasmate
Entering 'yasmate/bundles/html-tmbundle'
/home/user/.emacs.d/quelpa/build/yasnippet/yasmate/bundles/html-tmbundle
bundles/html-tmbundle
Entering 'yasmate/bundles/objc-tmbundle'
/home/user/.emacs.d/quelpa/build/yasnippet/yasmate/bundles/objc-tmbundle
bundles/objc-tmbundle
Entering 'yasmate/bundles/rails-tmbundle'
/home/user/.emacs.d/quelpa/build/yasnippet/yasmate/bundles/rails-tmbundle
bundles/rails-tmbundle
Entering 'yasmate/bundles/ruby-tmbundle'
/home/user/.emacs.d/quelpa/build/yasnippet/yasmate/bundles/ruby-tmbundle
bundles/ruby-tmbundle
Entering 'snippets'
error: pathspec 'snippets' did not match any file(s) known to git.
Did you forget to 'git add'?
Stopping at 'snippets'; script returned non-zero status.
```

**Comment by vyp** [comment]
I don't understand why it's being deinitialized in the first place? I saw #2903, but I don't understand why it has to be cleared out, shouldn't `git submodule update --init --recursive` be enough? Running `deinit` everytime seems suboptimal, isn't that more of a project-persist issue, rather than something that package-build should attempt to fix? Like shouldn't they have the emacs lisp equivalent of `make clean` before building? i.e. something equivalent to `make clean all` in their update process?

**Comment by vyp** [comment]
The reason the `deinit` command was introduced was to make it easier to *remove* submodules you're not interested in anymore. I'm not familiar with it being used as a 'reset' button like this. As in, my point is, there's clearly some artifact that's preventing project-persist from building (right?). So instead of essentially clearing out the submodule entirely before recloning it *all* again (recursively), shouldn't it be project-persist's job to figure out what the side effect is?

**Comment by purcell** [comment]
We had problems with submodule which changed their git URL over time. What would be the right way to update the submodule each time so that it handles that scenario?

**Comment by purcell** [comment]
In the meantime, I've reverted the corresponding commit in `package-build.el`.

**Comment by vyp** [comment]
If the remote url changes, wouldn't one have to manually edit `.git/config` and `.gitmodules` (or use `git config`)? How does `git submodule deinit` know about a url change? By my understanding, all `deinit` does is clear out the contents of the submodule (as in, on the disk), and removes the listing of it in `.git/config`, am I missing something?

Btw, reverting fixes the issue, but I will keep this open in case deinit is still needed, and the original bug comes back.

**Comment by vyp** [comment]
Also, `git submodule sync --recursive` should be the correct command (to update the submodule remote urls themselves) after editing `.git/config` and `.gitmodules`, assuming the different remote url still has the same git repository and git history, but I haven't tried it.

**Comment by purcell** [comment]
When a submodule URL changes upstream, it just changes `.gitmodules`, so what we're looking for is a command which re-syncs that URL to `.git/config` for the submodule. It's possible that `git submodule sync --recursive` does just that, so I'll try it out when I get a few minutes.

**Comment by vyp** [comment]
@purcell See the part for the `sync` command under `man git submodule` for what it means (officially).

**Comment by vyp** [comment]
Okay I just tried it for what you wanted, and it seems to work. If I understand correctly, the `.gitmodules` file has been changed to the new upstream url, but you still want to update `.git/config` with that new url. `git submodule sync --recursive` seems to do that. Not sure if the `--recursive` flag is needed though.

**Comment by vyp** [comment]
(Sorry for the multiple comments.) Actually I think you might need the `--recursive`, because it also updates all the submodules config files too (so `.git/modules/path/to/submodule/config`).

**Comment by purcell** [comment]
Thanks - yes, that looks perfect. Applied in c945038. Please give it a try and close this issue if everything works for you.

**Comment by vyp** [comment]
Looks good to me. Thanks very much. :smiley:

**Comment by purcell** [comment]
Great. My pleasure.
