### ISSUE TITLE
export/import function

### ISSUE THREAD

**Issue by Kejia** [milkypostman/melpa#2920]
when a user switches to a new computer, the user would like to re-install all previous packages from scratch rather than copying `.emacs.d'. given that melpa is becoming popular, it will be pretty useful to let users export a list of installed apps and install apps via importing the list.

**Comment by purcell** [comment]
I believe that `package.el` in the latest Emacs versions saves the installed packages into a custom variable, so you can just share custom config between the machines, or set that var in your emacs startup files.

Otherwise, `cask` and `pallet` can be used to handle this IIRC.

Hope that helps!
