### ISSUE TITLE
gitorious and sourceforge recipes temporarily down

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#2947]
gitorious is migrating to internet archive. sourceforge is doing some maintenance or something. anyways, just a heads up.

**Comment by milkypostman** [comment]
gitorious is still down. I am thinking about deleting the recipes for now since the original authors havent updated the recipes. then we can add back again later. OK?

**Comment by purcell** [comment]
Seems reasonable. How does this manifest itself as a problem? Messy logfiles, or disruption? Generally speaking, there will often be transient problems with recipes, e.g. outages of developers' personal git hosts etc.

**Comment by milkypostman** [comment]
no, the packages just start to be stale. i get two reports a day about packages that either dont exist or are expired. normally i dont pay much mind to this log but it reminds me to get in and clean things every once and a while.

for example, python-mode has an issue with them pushing versions back in time so the package becomes stale (there are actually two versions but the one we keep is old cause its a newer version number.) most of these I want to know about because it causes me to ping the author and tell them not to force push or something.

**Comment by purcell** [comment]
Cool. Happy to ditch these 4 recipes.
