### ISSUE TITLE
Seems helm-ls-git badge is not updating.

### ISSUE THREAD

**Issue by thierryvolpiatto** [milkypostman/melpa#2949]
helm-ls-git badge is stuck to "20150716.2200" but the last commit is of 2015/07/17.
It seems the file itself have been updated but not the badge.
Perhaps melpa is confused by the invalid tags I have pushed and then removed.

Thanks.

**Comment by purcell** [comment]
Yep, we have an issue due to an invalid package descriptor: https://github.com/jorgenschaefer/circe/pull/198.

I'll change the corresponding part of the build to make it more robust.

**Comment by purcell** [comment]
Workaround committed in 6e015a5, which should hopefully allow the build to recover.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Workaround committed in 6e015a5, which should hopefully allow the build to recover.

Thanks for your fix, but still at "20150716.2200", my last commit is at:

Date:   Fri Jul 17 12:14:06 2015 +0200

Maybe I have to wait tomorrow.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Okay, I just spent a while looking into this, and your last commit which touched a file in the package matches the current timestamp (in the server's timezone):

```
commit f321f5352c3ca4b0678cdead5716945290e15d4c
Author: Thierry Volpiatto <thierry.volpiatto@gmail.com>
Date:   Fri Jul 17 07:00:47 2015 +0200

    Fix defmethod with new source name for buffers.

    * helm-ls-git.el: Do it.
```

So everything is as it should be.

**Comment by purcell** [comment]
At some point it occurred to us it would have been better to use GMT timestamps, but switching over was going to be disruptive and possible cause installation failures, so we decided not to do it. :-)

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Okay, I just spent a while looking into this, and your last commit
> which touched a file in the package matches the current timestamp (in
> the server's timezone):

Ah! yes ok.

Thanks for your time on this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
