### ISSUE TITLE
Melpa doesn't build when rewrite git repository

### ISSUE THREAD

**Issue by marsam** [milkypostman/melpa#2981]
Hi:
I accidentally pushed an invalid commit in docker-tramp.el and after realizing I resetted the commit [1], but melpa still contains the old revision. 

I've checked the `package-build.el`, which contains the following command: `git reset --hard REV`, and I think that should be enough, but I'm not sure why still melpa contains the old revision. 

Sorry for the inconvenience.

[1] I know it's a bad practice, and I should have used `git revert` but in this case I prefered to use `git reset`.

**Comment by milkypostman** [comment]
Ok. We can fix it. Have to do it manually.

**Comment by Silex** [comment]
Oh oh, good to know about this, I often `push -f` when I'm the only dev of some repo.

**Comment by milkypostman** [comment]
Technically this shouldn't be an issue since we hard reset but sometimes if
a file conflicts it can cause issues.

**Comment by purcell** [comment]
@milkypostman Odd. A hard reset should wipe out conflicts too.

**Comment by milkypostman** [comment]
Oh, my bad. That wasn't the issue. It was building fine but the "mistake" was a newer version number than the other one and so it wasn't rolling back to the old version number.

we still haven't fixed the case where newer version numbers are lower than the previous build.

**Comment by milkypostman** [comment]
Fixed now.

**Comment by marsam** [comment]
Thanks a lot!
btw, shouldn't be better to keep this issue open?

**Comment by milkypostman** [comment]
Think we have another bug open for this already.
