### ISSUE TITLE
How do I change the name of my package?

### ISSUE THREAD

**Issue by kaz-yos** [milkypostman/melpa#2984]
I have a simple package called reveal-in-finder.el, which reveals the file associated with the current buffer in the Mac OS X finder. Someone pointed out the term finder is confusing in the emacs world, and it should be renamed to reveal-in-osx-finder.el. I think this is a reasonable thing to do, but I wasn't sure how to do this without breaking what is already on MELPA.

**Comment by milkypostman** [comment]
your package may break temporarily but that is ok. you will want to change your file name to `reveal-in-osx-finder.el` then submit a PR where you change the recipe to the new name. You'll want to add the `:old-names` directive to that recipe. Have a look at the [cider recipe](https://github.com/milkypostman/melpa/blob/master/recipes/cider) which was renamed from `nrepl`.

probably want to just have the new recipe PR ready to go before the rename.

**Comment by kaz-yos** [comment]
Thank you for you comment! I have updated the repository with the new name, and submitted a pull request.

Updated repo:
https://github.com/kaz-yos/reveal-in-osx-finder

Pull request to replace the outdated recipe file:
https://github.com/milkypostman/melpa/pull/2985
