### ISSUE TITLE
Cask integration?

### ISSUE THREAD

**Issue by fommil** [milkypostman/melpa#3001]
Hi, I was just wondering if there is any Cask integration for packages that you're adding to the repository? e.g. in ENSIME we'd like to be able to just have a `Cask` file and then you generate the `ensime-pkg.el` file automatically to save us from having to manage it, is that possible?

**Comment by purcell** [comment]
Nope. Just put the package metadata in the main .el file, and use Cask's `package-file` directive. If you're asking because of `:files` lists for the recipe, that's something we'd rather keep explicitly in our recipes. I'll go ahead and close this for now, but please feel free to discuss here.

**Comment by fommil** [comment]
So you're saying that I can define my dependencies in the comments of `ensime.el` and then you'll parse that to generate the `ensime-pkg.el` file for us? (and we can use `Cask` for our local dev)

**Comment by purcell** [comment]
Yes, exactly.

**Comment by fommil** [comment]
:smile:

**Comment by lunaryorn** [comment]
@fommil Just fyi, in the `Cask` file you'd use `(package-file "ensime.el")` to automatically extract the metadata from the comments for your `Cask` file :)

**Comment by fommil** [comment]
yup, already doing it thanks
