### ISSUE TITLE
Pull request not visible? 

### ISSUE THREAD

**Issue by ReneFroger** [milkypostman/melpa#3003]
I would like to add the package [recover-buffers](https://github.com/tripleee/recover-buffers), so I forked it and [created a pull request](https://github.com/ReneFroger/melpa/commit/3988ffbbb4a5e7b6e69de135186429d219755821). However, I don't see this pull request listed in the original MELPA repistory. So I assume I did something wrong?

**Comment by purcell** [comment]
Yes, it looks like you opened a pull request against your own repository, not against ours. Try it again, but with ours as the base.

**Comment by ReneFroger** [comment]
Thanks for your reply. And now?

**Comment by purcell** [comment]
yep, got it now. :-)
