### ISSUE TITLE
Broken link to emacs23 version of package.el

### ISSUE THREAD

**Issue by tripleee** [milkypostman/melpa#3008]
The README.md mentions an emacs23 version of `package.el` with a hyperlink to http://repo.or.cz/w/emacs.git/blob_plain/1a0a666f941c99882093d7bd08ced15033bc3f0c:/lisp/emacs-lisp/package.el but this link is currently a 404.

A working link would be much appreciated.

**Comment by purcell** [comment]
Thanks -- the link on the "getting started" page was correct, but this one was outdated: the emacs git repo got rewritten at some point, so all the SHA commit hashes changed.
