### ISSUE TITLE
package-build fails to build from emacswiki because of wrong page language

### ISSUE THREAD

**Issue by steckerhalter** [milkypostman/melpa#3033]
Emacswiki delivers cached pages and these are displayed in japanese for example sometimes. Then 'Last edited' cannot be found and throws an error (see issue here https://github.com/quelpa/quelpa/issues/77)

@kensanata suggested in https://github.com/emacsmirror/emacswiki.org/issues/5#issuecomment-132939665 that the date could also be fetched from the http headers when trying to get the source

Do you think that would be a good solution?

**Comment by purcell** [comment]
The language issue seems like an upstream problem, and I'd be wary of assuming that the `Last-Modified` time in the web server's response would always match the `Last edited` time on the page. So not sure what to do here. Perhaps we need to be explicitly sending an `Accept-Language` header?

**Comment by steckerhalter** [comment]
@kensanata [wrote](https://github.com/emacsmirror/emacswiki.org/issues/5#issuecomment-132939665):

> Note that you can also get the source code of wiki pages using raw in your info_path like this: http://www.emacswiki.org/emacs/raw/open-junk-file.el. And the wiki is smart enough to return the correct mtime in the Last-Modified header

So yes that should be good enough, but if you don't want to rely on that, the other option would be to specify the language in the url and disable the cache:

    http://www.emacswiki.org/emacs/open-junk-file.el?interface=en;cache=0

Although with that solution it is still more error-prone since if the template is being changed it could break again (even if the language is always correct).

**Comment by purcell** [comment]
Great. The former option would be better, then. Not sure when I'd get chance to work on this, but a PR would be welcome if you feel like poking around in `package-build.el`... :-)

**Comment by steckerhalter** [comment]
Allright, I'll see if I can poke a bit once in a while. Thanks
