### ISSUE TITLE
Updates appear as installable but not upgradeable

### ISSUE THREAD

**Issue by marsmining** [milkypostman/melpa#3058]
When I commit changes to my packages [repo](https://github.com/marsmining/ox-twbs), melpa updates ok, but when I use `M-x package-list-packages`, the package is shown as installable and installed on two different lines. If I choose to install the new version, I get both installed in my `elpa` directory.

Behavior I expect is one entry showing I can upgrade. Any suggestions?

**Comment by purcell** [comment]
That would be a `package.el` issue, not a MELPA issue -- you're doing everything right :-)

Which Emacs version do you have?

**Comment by marsmining** [comment]
Good to know. I'm using the dev tagged homebrew version. I'll try the normal one.

    GNU Emacs 24.5.50.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-06-19 on berlin

**Comment by purcell** [comment]
Yep, try grabbing a release version from emacsformacosx.com for easy testing.

**Comment by marsmining** [comment]
Ok, this appears to be my mis-understanding of the `package.el` interface, _not_ a problem with melpa.

Thanks for your help!

**Comment by purcell** [comment]
Great, glad you figured it out.
