### ISSUE TITLE
Wish: Are you gonna use gitter or slack for community discussion?

### ISSUE THREAD

**Issue by boyw165** [milkypostman/melpa#3155]
As title. :dancer:

**Comment by milkypostman** [comment]
Is there a public slack org?

**Comment by Silex** [comment]
@boyw165: what would gitter/slack improve over the classic issues workflow here?

**Comment by purcell** [comment]
Yeah, if the intention is to allow MELPA users or package authors to discuss things, then it might be an option, but I don't want there to be any expectation that I would provide any support via a chat system, because that's not something I'm going to do.

**Comment by milkypostman** [comment]
i don't get this. is there some public slack? i thought that everything was designed for specific groups/companies?

**Comment by boyw165** [comment]
Yeah the intention is for either package authors or beginners to discuss things. Actually we can create a specific group/co on the slack for it. How's it?

**Comment by tzz** [comment]
I think IRC would be the least common denominator among Emacs users, and the licensing model of Slack and Flowdock and others in that vein may be an issue.  Maybe just a `#melpa` IRC channel would be enough?

**Comment by Silex** [comment]
I'm also in favor of irc #melpa on freenode.

**Comment by milkypostman** [comment]
Yeah except I don't really use IRC all that much. At least not actively.
And creating a co on slack would be yet another thing I probably wouldn't
use.

Issues tend to be the best for us because we can do asynchronous comms with
least effort and history.

**Comment by milkypostman** [comment]
But someone should feel free to make the channel. I didn't mean to
discourage it. Just saying it's unlikely you would find myself or Steve in
there.

**Comment by purcell** [comment]
Agreed. I would never be in the IRC channel or Slack because it wouldn't decrease my already significant workload, and I'm not sure of the value of using "melpa" on freenode if none of the maintainers are involved. How do other comparable projects do this, like `homebrew`?

**Comment by Silex** [comment]
homebrew has an irc channel, but I think homebrew is much bigger than melpa so it's expected. To be honest I don't think #melpa will attract many users, there's already #emacs where people sometimes ask melpa-related questions... and I don't see melpa as being a topic discussed enough to justify a channel, but IMHO if we have to chose one irc is much better suited than giter/slack due to its "asynchronous chat" nature.
