### ISSUE TITLE
Update scheme of MELPA

### ISSUE THREAD

**Issue by ReneFroger** [milkypostman/melpa#3162]
If someone made changes to the code and commit it in their repository, you usually need to wait some hours, until you get the notification inside `package.el` that you could update a package from MELPA, because there is a newer version available to download.

I'm wondering what the scheme behind it is constructed. Does there fixed hours/time exists, where you need to wait exactly 2 hour before the update in `package.el` appears. E.g. every 3 hours or do you usue fixed hours for MELPA, e.g. the contents of all package will be checked on 15:00, 18:00, and so on? 

Thanks in advance for your reply.

**Comment by milkypostman** [comment]
it's not based on any time. it's just that we build all recipes, then wait
a while, then start again. think we wait 60 min between builds.

**Comment by purcell** [comment]
Polling all of the upstream repos is slow. To do things fundamentally more efficiently, we'd probably have to handle webhooks - at least for github - and this would likely involve running a small webapp on the server, which we don't currently do. And we'd still have to poll the repos, just in case we missed webhook callbacks. It's hard to see that it would all be worth the effort really.
