### ISSUE TITLE
Advice reguarding versions

### ISSUE THREAD

**Issue by Silex** [milkypostman/melpa#3166]
Hello,

I'd like to start versionning https://github.com/Silex/docker.el, but I'm unsure where to put the version (beside tagging the git repo).

For one-file projects you can just add a `Version` field in the header comments, but I'm not sure how to do it when there's multiple files and a `-pkg` file... if I look at https://github.com/magnars/dash.el it looks like each file includes some sort of version but that looks weird.

**Comment by purcell** [comment]
Here's the MELPA answer; just put the version number in the tag, and don't worry about putting it in the individual files.

**Comment by purcell** [comment]
(Closing, but feel free to discuss further.)

**Comment by Silex** [comment]
Okay, even for single-file repos?

**Comment by purcell** [comment]
Yep. I often put something like `Version: 0` in the headers of my single-file packages, if you care about being able to check the syntax of a single-file package with `flycheck-package` (which you should :-)).

**Comment by Silex** [comment]
Alright, thanks for the advices!
