### ISSUE TITLE
idea: add "Next build in... " information on website

### ISSUE THREAD

**Issue by Silex** [milkypostman/melpa#3192]
Hello,

Currently I see on http://melpa.org that `Last build ended: 3 hours ago`.

It'd be nice if we had `Next build in: ~53 minutes` information somewhere, even if incorrect.

Simply store the last build time somewhere, and then do some math extrapolation to guess when the current build is going to finish.

Actually, the information could be like this:

```
Last build ended: $(now - last_build_end) hours ago
Current build ends at: $(current_build_start + (last_build_end - last_build_start))
Next build starts at: $(current_build_start + (last_build_end - last_build_start) + 30)
```

You get the idea :)

**Comment by Silex** [comment]
Closing for the PR

**Comment by purcell** [comment]
`[0-9]+` should always work, I guess.
