### ISSUE TITLE
MELPA stable website shows incorrect version numbers

### ISSUE THREAD

**Issue by Wilfred** [milkypostman/melpa#3205]
E.g. https://stable.melpa.org/#/racer shows 1.0.0 even though the current release is 0.0.2.

**Comment by milkypostman** [comment]
i have fixed the issue it should apply now.

did you previously have a 1.0.0 version? the server seems to think so and we expire old packages based on version number not timestamp. in the case that a new version has a smaller version number then we delete the newly built package. The idea being that a version should never really get smaller.

**Comment by Wilfred** [comment]
Aha! We didn't have a 1.0.0 in this repo, but the repo has changed. Previously racer.el was in the same repo as the racer tool itself, so presumably MELPA has remembered tags from the previous repo.

Presumably this means melpa stable users may have installed a 1.0.0 and they won't have been upgraded. We should probably create a 1.0.1 tag in the current repo to ensure everyone is on the latest release.

**Comment by purcell** [comment]
> We should probably create a 1.0.1 tag in the current repo to ensure everyone is on the latest release.

Yep, that would make sense.

**Comment by milkypostman** [comment]
yeah, stable has a problem that we cannot distinguish multiple projects in
the same repo :*(  it's a problem we can solve but it's not high enough
priority.
