### ISSUE TITLE
recipes/clang-format fetches from LLVM svn, new argument breaks package for 99% users

### ISSUE THREAD

**Issue by AlKapote** [milkypostman/melpa#3221]
LLVM 3.8 adds a new argument called `-sort-includes` to their source code formatter and
have updated their `.el` (on svn trunk) to pass it by default when calling the binary. 
MELPA unstable fetches from SVN, but practically everyone who uses MELPA will be on 3.7 or less for quite a while. 

There also doesn't seem to be a clang-format on stable. 

cc @kljohann who is on the hook forever because he opened https://github.com/milkypostman/melpa/pull/1654 and then https://github.com/milkypostman/melpa/pull/2399.

**Comment by purcell** [comment]
Yeah, we don't yet support version tags in SVN repos, so that's why it doesn't appear in stable. (See #2075 for more on this general topic.)

I'd be very grateful for some help adding `stable` support to the `svn` builder in `package-build.el` if you or another contributor would like to have a poke around.

Nonetheless, this specific issue here isn't really a MELPA problem, because the MELPA snapshot version of this package contains the intended development version of `clang-format.el`, so I'm going to close it, sorry.

**Comment by AlKapote** [comment]
Would you accept a `clang-format-3.7` recipe (from github) as a "right-now" solution? When I or someone else writes the svn tag support it can be removed in favor of a stable package.

Practically everyone who is using this package now, can't.

**Comment by AlKapote** [comment]
What about using the github mirror? updated every 5 minutes.

Stable (3.7): https://github.com/llvm-mirror/clang/blob/release_37/tools/clang-format/clang-format.el
Trunk: https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/clang-format.el

**Comment by kljohann** [comment]
If only the git repo had tagged releases which we could use for melpa-stable… Personally I would prefer an upstream patch that made the `-sort-includes` flag configurable compared to N different clang-format packages on melpa.

**Comment by AlKapote** [comment]
It has branches instead of tags, that shouldn't be an issue.

But actually anyone who has clang installed already has the version-appropriate version of .el somewhere on their system. This package should either not exist or should just be a shim that finds the local version and loads it.

**Comment by AlKapote** [comment]
```elisp
(require 'cl-lib)

(defvar clang-format-search-relpath-list '("share/clang")
  "List of locations to search for 'clang-format.el' in. Contains dirnames relative to llvm-config --prefix")

(defun my/find-clang-format-dir ()
  (cl-loop
     with llvm-prefix = (string-trim (shell-command-to-string "llvm-config --prefix"))
     for relpath in clang-format-search-relpath-list
     for dir = (mapconcat 'file-name-as-directory (list llvm-prefix relpath) "")
     for path = (concat dir "clang-format.el")
     until (file-exists-p path)
     finally return dir))

(if (not (my/find-clang-format-dir))
    (message "clang-format.el not found. Please set 'clang-format-search-relpath-list'")
  (add-to-list 'load-path (my/find-clang-format-dir))
  (require 'clang-format))

;(provide 'local-clang-format-loader)
```

**Comment by syohex** [comment]
`-sort-include` option issue on older clang users was fixed by following commit. Please upgrade clang-format.el and try again.

https://github.com/llvm-mirror/clang/commit/d27c92ca6f5fcafbe4c63f6e2bc440f0e86f881a#diff-e094070cb41c78c4a39f1b870dd8827b
