### ISSUE TITLE
Building seems to be stuck?

### ISSUE THREAD

**Issue by Silex** [milkypostman/melpa#3223]
`Current build started: a day ago, last took 4 hours`

I noticed because I'm trying to install `magit-rockstar` which was added yesterday, and as it was still not there this morning I checked.

@purcell ;)

**Comment by vyp** [comment]
Current build started: 12 minutes ago, last took 4 hours

Maybe it was fixed by https://github.com/milkypostman/melpa/commit/6a1faf35d475b4c608e3071c3405d3def855298a?

**Comment by Silex** [comment]
Alright :)
