### ISSUE TITLE
melpa badges are not up to date

### ISSUE THREAD

**Issue by ptrv** [milkypostman/melpa#3235]
The melpa badges are not up to date. See package [ycmd](http://melpa.org/#/ycmd) or [flycheck](http://melpa.org/#/flycheck). The dates are not matching the ones from the title.

**Comment by milkypostman** [comment]
looking into this.

**Comment by milkypostman** [comment]
the pull code for images is broken for some reason

**Comment by milkypostman** [comment]
```
$ gnutls-cli img.shields.io
Resolving 'img.shields.io'...
Connecting to '104.18.45.160:443'...
*** Fatal error: A TLS fatal alert has been received.
*** Received alert [40]: Handshake failed
*** Handshake has failed
GnuTLS error: A TLS fatal alert has been received.
```

something is wrong with modern gnutls on ubuntu with our imgshields code. i will keep digging when I get a chance. not sure why this is failing but it's only with version 24.3 of emacs.

**Comment by rexim** [comment]
Also, we don't have a badge for [psc-ide](http://melpa.org/#/psc-ide)

http://melpa.org/packages/psc-ide-badge.svg returns 404

Could it be related to this issue? The package was added recently: https://github.com/milkypostman/melpa/pull/3215

**Comment by cpaulik** [comment]
Could this be related to me getting an error when trying to build a new recipe?

This is what I get when I run `make recipes/live-py-mode`:

```shell
File: /home/cp/workspace/emacs/melpa/packages/live-py-mode-20150724.2151.entry
Contacting host: img.shields.io:80
gnutls.c: [0] (Emacs) fatal error: A TLS fatal alert has been received.
gnutls.c: [0] (Emacs) Received alert:  Internal error
gnutls.el: (err=[-12] A TLS fatal alert has been received.) boot: (:priority NORMAL :hostname img.shields.io :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
error in process filter: GnuTLS error: #<process img.shields.io<1>>, -12
Makefile:88: recipe for target 'recipes/live-py-mode' failed
```

This is on ArchLinux with emacs 24.5.1

**Comment by milkypostman** [comment]
Same bug. I'm going to modify the script to use curl temporarily but
haven't had a free moment to do so.

**Comment by purcell** [comment]
Workaround added in cf06171. Not sure if it will have any effect on existing packages until they get replaced though.

**Comment by netromdk** [comment]
That fixed it for me. Thanks!

**Comment by cpaulik** [comment]
Thanks, this also fixed it for me.

**Comment by purcell** [comment]
Thanks folks!
