### ISSUE TITLE
New projectile release not being picked up by melpa-stable

### ISSUE THREAD

**Issue by mdorman** [milkypostman/melpa#3239]
@bbatsov tagged 0.13.0 five days ago (https://github.com/bbatsov/projectile/releases/tag/v0.13.0), but melpa-stable is still declaring 0.12.0 to be the latest version.  Seems like something's stuck?

**Comment by thierryvolpiatto** [comment]
Same for helm tagged two days ago.

Thanks.

**Comment by purcell** [comment]
I gave the server a kick - let's give it a couple of hours and see if it sorts itself out.

**Comment by purcell** [comment]
`helm` is working now, at least, and `projectile` should get rebuilt soon.

**Comment by purcell** [comment]
(Note that badges are currently broken, but that's a separate issue.)

**Comment by thierryvolpiatto** [comment]
Ok, thanks for looking into this.
