### ISSUE TITLE
bonjourmadame package needs a NSFW warning in its package description

### ISSUE THREAD

**Issue by greenrd** [milkypostman/melpa#3248]
Even visiting the web page to see what it is, is NSFW (Not Safe For Work).

The README in the bonjourmadame repo already has a NSFW warning, but the README displayed in emacs does not.

**Comment by purcell** [comment]
Our description comes the `Commentary` in the upstream `.el` file, and is not under our control. Probably a quick PR to https://github.com/pierre-lecocq/bonjourmadame would fix this.
