### ISSUE TITLE
Flycheck is not available

### ISSUE THREAD

**Issue by d12frosted** [milkypostman/melpa#3266]
[Recipe](https://github.com/milkypostman/melpa/blob/master/recipes/flycheck) is on it's place. But [Flycheck page on MELPA](http://melpa.org/#/flycheck) says that package is not available. Also can't it install using `package-install` with MELPA in `package-archive` list. On MELPA stable it's available.

**Comment by milkypostman** [comment]
this is my bad. accidentally removed it temporarily. back soon.

**Comment by milkypostman** [comment]
like now

**Comment by d12frosted** [comment]
Thank you very much for quick solution.
