### ISSUE TITLE
Failed to download `melpa' archive

### ISSUE THREAD

**Issue by lyqscmy** [milkypostman/melpa#3307]
I only add this in my init.el.
``` lisp
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```

when I refresh packages, I got error.

``` lisp
Debugger entered--Lisp error: (file-error "https://melpa.org/packages/archive-contents" "Not implemented")
  signal(file-error ("https://melpa.org/packages/archive-contents" "Not implemented"))
  url-insert-file-contents("https://melpa.org/packages/archive-contents")
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents")
  #[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"]()
  funcall(#[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"])
  package-refresh-contents()
  package-menu-refresh()
  call-interactively(package-menu-refresh nil nil)
  command-execute(package-menu-refresh)
```

It seems to lack '/'  after  'archive-contents' in url-insert-file-contents("https://melpa.org/packages/archive-contents").

How to fix it?

**Comment by lyqscmy** [comment]
Same init.el works fine on windows, while got error on Ubuntu15.10 in  emacs24.5.

**Comment by syohex** [comment]
Could you try http instead https as below ? I suppose if you success with http, TLS package(like gnutls) is not installed on your environment.

```
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
```

**Comment by lyqscmy** [comment]
@syohex  I tried and got the same error.

**Comment by syohex** [comment]
I cannot reproduce this issue on my Ubuntu 15.10 and Ubuntu package Emacs-24.5.1.
Do you use proxy ?

**Comment by lyqscmy** [comment]
@syohex  You are right.It's my proxy problem.But I can't connect melpa without proxy.

However, I can got response from in browser when request https://melpa.org/packages/archive-contents.

**Comment by syohex** [comment]
Do you set `url-proxy-services` ?

```lisp
(setq url-proxy-services 
      '(("http" . "proxy.example.com:8080")
        ("https" . "proxy.example.com:8080")))
```

**Comment by lyqscmy** [comment]
@syohex  

Maybe it's my proxy provider's problem.It really works fine on windows.On linux,browser and terminal both work well with proxy.

``` shell
 curl https://melpa.org/packages/archive-contens >> melpa.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0     74      0  0:00:02  0:00:02 --:--:--    74
```

Even I set proxy in terminal and start emacs from it , still didn't work.

Despair and angry!

**Comment by lyqscmy** [comment]
@syohex I captured the IP packets between emas and melpa with tcpdump.It shows that the traffic is healthy.However,the minibuffer still show "contacting ..." after server finishing session.
Is this a bug?

**Comment by syohex** [comment]
> However,the minibuffer still show "contacting ..." after server finishing session.
> Is this a bug?

No. Last message continues to remain in minibuffer until another message is shown. However I suppose implementation of package.el is not good. It should do `(message nil)` after server finishing session.
