### ISSUE TITLE
flycheck package does not install

### ISSUE THREAD

**Issue by jwintz** [milkypostman/melpa#3312]
Hello,

`M-x install-package flycheck` reports: error: Package `let-alist-1.0.4' is unavailable

Is it a missing dependency on MELPA ?

Thanks !

**Comment by syohex** [comment]
`let-alist` is hosted on GNU ELPA. You need to set GNU ELPA archive to `package-archives` variable.

https://elpa.gnu.org/packages/let-alist.html

**Comment by jwintz** [comment]
Here is my package configuration:

```
 (setq package-archives '())

 (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
 (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
 (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))

 (package-refresh-contents)

 (package-initialize)
```

It seems to me that gnu elpa is taken into account when searching for packages but I can unfortunately not find `let-alist`.

**Comment by syohex** [comment]
I can see `let-alist` with you configuration.

![screen shot 2015-11-20 at 10 58 05 pm](https://cloud.githubusercontent.com/assets/554281/11301407/4ca36dd8-8fda-11e5-89ea-05d62dd0df9a.png)

**Comment by syohex** [comment]
Please check `~/.emacs.d/elpa/archives/gnu/archive-contents`. If you cannot find `let-alist` from it, I suppose you fail to download archive information.

**Comment by jwintz** [comment]
Here is the problem. I have no `gnu` directory in `elpa/archives`. Only `marmalade` and `elpa`.

![screen shot 2015-11-20 at 15 05 28](https://cloud.githubusercontent.com/assets/3277054/11301533/3e18c804-8f98-11e5-903e-5709a55e1371.png)

How is this possible ?

**Comment by syohex** [comment]
GNU repository is not stable rather than melpa.  Downloading archive information is sometimes failed. Please try `package-refresh-contents`  again.

**Comment by jwintz** [comment]
`package-refresh-contents` is in my initialization.

I however run this command again, then list all packages:
* `M-x package-refresh-contents`
* `M-x package-list-packages`

I assume that the last command calls also `package-refresh-contents` and I can see elpa in the mini buffer very quickly, but ~/.emacs.d/prolusion-elpa/archives/ still does not contain the gnu folder.

**Comment by jwintz** [comment]
Ok, I tried on a friend's machine and it appears that it is a **built-in** package, for newer emacs versions.

* He has emacs 25.0.50
* I have emacs 24.4.50

I'll try to upgrade my emacs to solve my problem but it is still very strange that I can't touch GNU ELPA.

**Comment by jwintz** [comment]
Ok, I update to 25.1.50.1 and I am not able to fetch any content anymore.

I'm closing the ticket as my problem obviously does not come from MELPA.

Thanks anyway !

**Comment by purcell** [comment]
P.S. Your melpa URL is outdated -- please see the README or our "Getting Started" page for up-to-date set-up instructions.

**Comment by jwintz** [comment]
Updated. Thanks Steve !
