### ISSUE TITLE
MELPA won't pull in newer versions of scpaste

### ISSUE THREAD

**Issue by Jehops** [milkypostman/melpa#3334]
The package `scpaste` is stuck at code from 2011 on MELPA.  I noticed that the `Package-Version` header in `scpaste.el` has been removed and now there is only a `Version` header.  Is there a fix for this on MELPA or will the package need to be updated?

**Comment by milkypostman** [comment]
scpaste is pulled from the wiki page http://www.emacswiki.org/emacs/scpaste.el

if you look at the bottom the last time this was updated was 2011. If there is a better repo (git or something) then we'd be happy to use that if it's the *official* channel.

**Comment by Jehops** [comment]
Ah, of course I see that in the package now.  Thanks for clarifying.  Yes, the official channel is here: https://github.com/technomancy/scpaste.  Does a new recipe need to be submitted?

**Comment by milkypostman** [comment]
Done. Later. :+1:
