### ISSUE TITLE
Packages that are also available from GNU Elpa

### ISSUE THREAD

**Issue by tarsius** [milkypostman/melpa#3383]
The following packages are available from Melpa as well as from GNU Melpa.  In some cases this is probably the right thing to do, in others not so much.

### Packages that I think *should* probably be remove from Melpa

- [x] [vlf](https://github.com/m00natic/vlfi)
- [x] [web-server](https://github.com/eschulte/emacs-web-server)

These repositories have not been updated in quite some time (more than half a year) that probably means that development now happens in the GNU Elpa repository.  Or if these packages are "done" then bugfixes probably only happen in GNU Elpa and do not get merged back to the repositories on Github.

@m00natic and @eschulte please let us know which is the case.

- [x] [seq](https://github.com/NicolasPetton/seq.el)

In addition to being available from both GNU Elpa and Melpa, it also will be part of Emacs v25.1.  That seems like a bit much.

@NicolasPetton where does development happen?  Elpa, Melpa, or Emacs?  Are all three versions identical (though possibly out of sync at times), or is one of these versions a backport?

### Packages that I think should probably *not* be remove from Melpa

- [x] [ergoemacs-mode](https://github.com/ergoemacs/ergoemacs-mode)
- [x] [pabbrev](https://github.com/phillord/pabbrev)
- [x] [ahungry-theme](https://github.com/ahungry/color-theme-ahungry)
- [x] [easy-kill](https://github.com/leoliu/easy-kill)
- [x] [names](https://github.com/Malabarba/names)
- [x] [ztree](https://github.com/fourier/ztree)

These repositories have seen updates during the last six months, so it appears they are still being actively worked on.  Never-the-less I would like to know from @ergoemacs, @phillord, @ahungry, @leoliu, @Malabarba, and @fourier

1. Should your package remain on Melpa? Why?
2. Where does development happen primarily?
3. How are the repositories synced?
4. How often do you sync?
5. Do commits flow in both directions?

If the answer to (1) is "yes", then I'll probably also mirror your Github repository on the Emacsmirror.

I expcet that for `ergoemacs-mode` and `paabbrev` (3) should be trivial because they use dedicated branches in the Elpa repository.  But for the others this is less clear.  Do you use `git subtree` or do you do you just dump a version into the Elpa repository and create a commit "update to version X"?

### Lets talk about subtrees

If you do use `git subtree`, then please also describe your workflow.  While I much preferred it if the Elpa repository used a separate branch for each package (or even a separate repository) the current approach forces the use of `git subtree` (or giving up on proper merges).

I hope that eventually the Elpa repository will use one branch per package and one `master` branch which tracks all the package branches as submodules.  But that's not the issue here - for now we are stuck with `git subtree` (which some of you might actually prefer) or doing it by hand.

I am considering adding support for `git subtree` to Magit - sharing your workflow will make it easier to get this right.

**Comment by fourier** [comment]
I'm planning to keep github and therefore MELPA as a primary source of development and only from time to time release to GNU ELPA(more/less stable versions, while MELPA shall contain up-to-date versions). I use `git subtree` for it. I don't have any specific process for it; if anything better will be suggested I'll be happy
Even if the `ztree` will be removed from MELPA it probably would still be developed only in github anyway.

**Comment by m00natic** [comment]
There's more to come from VLF, it's just that I haven't had much energy
to go for new features last year.  Anyway, I prefer development to
happen in github/MELPA where more experimental stuff can land.  I only
push stable release patches to GNU ELPA.

**Comment by tarsius** [comment]
@fourier @m00natic Thanks for the information. I am now mirroring your repositories.

**Comment by Malabarba** [comment]
Just so you know, I have a couple more packages on both repos. Not sure if you intentionally omitted them here or if your algorithm missed something. 

> 1. Should your package remain on Melpa? Why?

I like that aggressive-indent is on Melpa. Because it's fairly popular and fairly complicated, so it's good to have volunteers to test the snapshots. 
I don't care about beacon or Names. Names is there simply due to history. Beacon wasn't added to Melpa by me. 

> 2. Where does development happen primarily?

Github repo. 

> 3. How are the repositories synced?

Git subtree pull. 

> 4. How often do you sync?

As often as you would normally tag a new release on Melpa-stable. Only instead of tagging I subtree pull. 

> 5. Do commits flow in both directions?

No. I commit to github and pull to elpa.git. If someone edits the package on elpa.git (which happens somewhat rarely), I copy the changes to github manually. 

> Are all three versions [of seq] identical (though possibly out of sync at times), or is one of these versions a backport?

No. The version on the emacs repo is different. It uses some new infrastructure in order to apply to generalised sequences (while providing the same api).

**Comment by ahungry** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> These repositories have seen updates during the last six months, so it
> appears they are still being actively worked on.  Never-the-less I
> would like to know from @ergoemacs, @phillord, @ahungry, @leoliu,
> @Malabarba, and @fourier
>
> 1. Should your package remain on Melpa? Why?
> 2. Where does development happen primarily?
> 3. How are the repositories synced?
> 4. How often do you sync?
> 5. Do commits flow in both directions?
>
> If the answer to (1) is "yes", then I'll probably also mirror your Github repository on the Emacsmirror.
> ...<snip>...
> If you do use `git subtree`, then please also explain your workflow.
> While I much prefered it if the Elpa repository used a separate branch
> for each package (or even a separate repository) the current approach
> forces the use of `git subtree` (or giving up on proper merges).
>
> I hope that eventually the Elpa repository uses one branch per package
> and one branch which tracks all the package branches as submodules.
> But that's not the issue here - for now we are stuck with `git
> subtree` (which some of you might actually prefer) or doing it by
> hand.
>
> I am considering adding support for `git subtree` to Magit - sharing your workflow will make it easier to get this right.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/milkypostman/melpa/issues/3383

1.  I don't think it can hurt (it can be a slight bit ahead commit wise)
- it was added to MELPA prior to GNU Elpa.

2.  I develop on the github repo (that MELPA pulls from) and bring in to GNU
Elpa via git subtree.

3.  The repositories are synced via git subtree.

4.  Pretty often (GNU Elpa is only ever a day or so behind MELPA, if at
all - only if I make updates on a machine that I don't have the GNU Elpa
source checked out on and have to subtree it in later).

5.  No one has updated but myself, and I follow the consistent work flow
but, similar to Artur, if someone were to, I would likely manually make
their changes on my github and ensure both were matching again.

-- 
Matthew Carter (m@ahungry.com)
http://ahungry.com

**Comment by leoliu** [comment]
I am answering for easy-kill. inlined.

> On 2015年12月14日, at 00:01, Jonas Bernoulli <notifications@github.com> wrote:
> 
> The following packages are available from Melpa as well as from GNU Melpa. In some cases this is probably the right thing to do, in others not so much.
> 
> Packages that I think should probably be remove from Melpa
> 
> vlfi
> web-server
> These repositories have not been updated in quite some time (more than half a year) that probably means that development now happens in the GNU Elpa repository. Or if these packages are "done" then bugfixes probably only happen in GNU Elpa and do not get merged back to the repositories on Github.
> 
> @m00natic and @eschulte please let us know which is the case.
> 
> seq
> In addition to being available from both GNU Elpa and Melpa, it also will be part of Emacs v25.1. That seems like a bit much.
> 
> @NicolasPetton where does development happen? Elpa, Melpa, or Emacs? Are all three versions identical (though possibly out of sync at times), or is one of these versions a backport?
> 
> Packages that I think should probably not be remove from Melpa
> 
> ergoemacs-mode
> pabbrev
> ahungry-theme
> easy-kill
> names
> ztree
> These repositories have seen updates during the last six months, so it appears they are still being actively worked on. Never-the-less I would like to know from @ergoemacs, @phillord, @ahungry, @leoliu, @Malabarba, and @fourier
> 
> Should your package remain on Melpa? Why?
Yes. See below.

> Where does development happen primarily?

github
> How are the repositories synced?

git pull -s subtree to gnu elpa
> How often do you sync?

normally when a new release is tagged
> Do commits flow in both directions?

yes

so far all commits are made in github then subtree merge to gnu elpa.

**Comment by NicolasPetton** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> - [seq](https://github.com/NicolasPetton/seq.el)
>
> In addition to being available from both GNU Elpa and Melpa, it also
> will be part of Emacs v25.1.  That seems like a bit much.

Indeed, adding it to MELPA was probaby a mistake.

>
> @NicolasPetton where does development happen?  Elpa, Melpa, or Emacs?
> Are all three versions identical (though possibly out of sync at
> times), or is one of these versions a backport?

Development happens in Emacs, but the version in GELPA and Melpa are
backward-compatible with Emacs 24, and yes, they are identical.

**Comment by tarsius** [comment]
I'v opened  #3387 to have `seq` removed from Melpa.

**Comment by tarsius** [comment]
@ahungry I am not adding any more themes to the Emacsmirror so I am not adding this one either even though it is part of GNU Elpa. (Actually I had to remove it because the assert that should have kept me from adding it did not kick in when mirroring packages from Elpa.)

@purcell @milkypostman I would remove this from Marmalade. But it also does no harm if this stays, so I am not creating a pr for that (unless you ask me to).

**Comment by tarsius** [comment]
@leoliu I am mirroring you repository on the Emacsmirror now.

**Comment by tarsius** [comment]
@Malabarba 

> Just so you know, I have a couple more packages on both repos. Not sure if you intentionally omitted them here or if your algorithm missed something.

Yes I know. I was just concentrating on those packages that are available from Melpa and GNU Elpa for now. The Emacsmirror gets `names` from you repository too now.

I've now also gone through the list of all your elisp repositories and discovered that the following packages are missing from the Emacsmirror and Melpa:

* brightness
* display-keys
* elisp-bug-hunter
* greek-unicode-insert
* lisp-assistant
* markdown-to-lisp-comments
* spinner (only missing from Melpa)
* weaver (you should rename the repository)

I have created a pull request to add these packages to Melpa and will later add them to the Emacsmirror too.  Should any of these packages not be added to Melpa and the Emacsmirror?

There are also two non-package elisp repositories which are not included in the pr.

* ox-jekyll-subtree
* emacs-archive-tracker

**Comment by tarsius** [comment]
Now fixing `bug-hunter`.

**Comment by phillord** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> The following packages are available from Melpa as well as from GNU Melpa. In
> some cases this is probably the right thing to do, in others not so much.
> These repositories have seen updates during the last six months, so it appears
> they are still being actively worked on. Never-the-less I would like to know
> from @ergoemacs, @phillord, @ahungry, @leoliu, @Malabarba, and @fourier
>
> 1. Should your package remain on Melpa? Why?


Probably for the moment, yes. It has download stats which are fun from
an ego point-of-view.

> 2. Where does development happen primarily?

Usually on a computer.

> 3. How are the repositories synced?
> 4. How often do you sync?

I try and push to both ELPA and github.

I've just found you can push to two repos at once which is a nice thing.

> 5. Do commits flow in both directions?

Yes, commits have gone in both directions. Not many, but then pabbrev
was largely complete before it went into git. Commits from ELPA are
often cosmetic, although in the case of pabbrev, Stefan made a
significant change to the implementation.


> I expcet that for `ergoemacs-mode` and `paabbrev` (3) should be trivial
> because they use dedicated branches in the Elpa repository. But for the others
> this is less clear. Do you use `git subtree` or do you do you just dump a
> version into the Elpa repository and create a commit "update to version X"?
>
> If you do use `git subtree`, then please also explain your workflow. While I
> much prefered it if the Elpa repository used a separate branch for each
> package (or even a separate repository) the current approach forces the use of
> `git subtree` (or giving up on proper merges).


I used an "external branch" because it seemed simpler to me. Mostly,
though, this was an expression of ignorance. I didn't know that there
was a git subtree command -- I assumed everyone was using a single ELPA
repo. This was a pain for me, because I unison my home space around
(including many git repos), and ELPA was too large. For this reason,
I added both pabbrev, omn-mode and dash as externals.

It mostly worked, although keeping the various branches straight in my
mind can be a little difficult.


> I hope that eventually the Elpa repository uses one branch per package and one
> branch which tracks all the package branches as submodules. But that's not the
> issue here - for now we are stuck with `git subtree` (which some of you might
> actually prefer) or doing it by hand.

From the question, you imply that external branches is superior to
subtrees. I'd be interested in knowing why; I was thinking to add a new
package via subtrees just so I could compare.


> I am considering adding support for `git subtree` to Magit - sharing
> your workflow will make it easier to get this right.


I guess my answer hasn't helped with this!

Phil

**Comment by purcell** [comment]
> > 2. Where does development happen primarily?
> Usually on a computer.

LOL

**Comment by Malabarba** [comment]
@tarsius 

>> Just so you know, I have a couple more packages on both repos. Not sure if you intentionally omitted them here or if your algorithm missed something.

> Yes I know. I was just concentrating on those packages that are available from Melpa and GNU Elpa for now. The Emacsmirror gets  names  from you repository too now.

Maybe I wasn't clear. The "other packages" I was referring to are indeed available from both Melpa and GNU Elpa. These are just aggressive-indent and beacon (those repos you listed are not packages (yet)).

**Comment by tarsius** [comment]
Except `bug-hunter` and `spinner`, those are packages too. Right?

**Comment by Malabarba** [comment]
@tarsius yes :)

**Comment by eschulte** [comment]
I think web-server can be removed from MELPA.  I'm already committed to
pushing bug fixes to the GNU ELPA, so there probably isn't a need for a
separate ELPA tracking this project.

Note, although I haven't pushed to this for a while, I am still actively
maintaining it, I just haven't received any issues, or bugs in a long while
now (which maybe isn't too surprising for a fairly simple project).

Note: I see six project which depend on web-server in MELPA.  I assume
those will continue to function if web-server is removed from MELPA and
they'll automatically pull web-server from the GNU ELPA?

Thanks,
Eric

**Comment by tarsius** [comment]
Lol. I was just right now looking at this package in more depth.

**Comment by tarsius** [comment]
> I think web-server can be removed from MELPA.

I agree. There hasn't been much activity in either repository, but there's one commit in Elpa which has not yet made it's way back into your package.

> I am still actively maintaining it

Good to hear.

> I assume those will continue to function if web-server is removed from MELPA and they'll automatically pull web-server from the GNU ELPA?

Yes.

Thanks to you too

**Comment by tarsius** [comment]
Oh, and I will create a pr to remove the recipe.

**Comment by tarsius** [comment]
Which leaves just one, `ergoemacs-mode`. And for that we probably haven't gotten a reply yet because I did mention the name of the organisation instead of the maintainer. This is actively maintained on Github, so it should in all likelihood stay in Melpa, but lets ask @mattfidler anyway.

**Comment by mattfidler** [comment]
Should your package remain on Melpa? Why?
I also like that ergoemacs-mode is on melpa.  

Where does development happen primarily?
Github repo.

How are the repositories synced?
I push to the repository once a stable branch is committed.  I was hoping to get a stable branch to submit it to the gnu repository, since it is currently out of date.

How often do you sync?
As often as you would normally tag a new release on Melpa-stable. 

Do commits flow in both directions?
No. I commit to github and push to elpa.git. I don't think anyone has ever changed the github repository, so I haven't changed it...

Are all three versions [of seq] identical (though possibly out of sync at times), or is one of these versions a backport?

Yes

**Comment by mattfidler** [comment]
I looked at the gnu repository and saw that Stefan indeed made some contributions at the beginning of the year to make ergoemacs-mode work with the updated eieio;  They are not in the repository, and I have taken out eieio dependence.

**Comment by tarsius** [comment]
Thanks again everyone!
