### ISSUE TITLE
Package gets build locally but the tar on melpa.org is incomplete

### ISSUE THREAD

**Issue by dvhansen** [milkypostman/melpa#3402]
No idea what's going wrong.  Locally I get:

```
[dhansen@localhorst melpa] $ make recipes/python3-info
 • Building recipe python3-info ...
 […]

[dhansen@localhorst melpa] $ tar --list -f packages/python3-info-20151117.731.tar
python3-info-20151117.731/
python3-info-20151117.731/dir
python3-info-20151117.731/python.info
python3-info-20151117.731/python.info-34
python3-info-20151117.731/python.info-33
[…]
python3-info-20151117.731/python3-info-pkg.el
python3-info-20151117.731/python3-info.el
[dhansen@localhorst melpa] $
```

but when I download the package from melpa.org:

```
[dhansen@localhorst melpa] $ wget -qO - https://melpa.org/packages/python3-info-20151116.2231.tar | tar --list
python3-info-20151116.2231/
python3-info-20151116.2231/python3-info.el
python3-info-20151116.2231/python3-info-pkg.el
[dhansen@localhorst melpa] $
```

The .texi file is rather huge >10M.  May this be the problem?

**Comment by milkypostman** [comment]
yes, i haven't gotten around to figuring out a fix for this style of thing.
python3-info and python-info are not consistently building correctly
because the packages are just too big. I actually think we may have to
remove them.

**Comment by milkypostman** [comment]
I pinged @Wilfred on #1037 to see what he says. At this point I don't know that it makes sense to increase the server size just for this one package.

**Comment by milkypostman** [comment]
0679e8939bd82642a771f63eb5d2b71ef12f7daa is trying to fix this for python and python3 info packages. 

closing, please let me know if it doesn't work.
