### ISSUE TITLE
minibuf-isearch repo no longer accessible

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#3406]
not sure what's going on here, needs more investigation

**Comment by lurdan** [comment]
The svn repository hosting coderepos.org seems to be down (at least after 2015, August)

Though svn enhancements are lost (if any), minibuf-isearch can be fetched from original distribution:
http://www.sodan.org/~knagano/emacs/minibuf-isearch/minibuf-isearch.el

**Comment by purcell** [comment]
@lurdan We don't support fetching from non-version-controlled sources, unfortunately.

**Comment by lurdan** [comment]
@knagano Could you please host minibuf-isearch on github (or so)?

**Comment by knagano** [comment]
@lurdan Okay. Here it is. https://github.com/knagano/minibuf-isearch

**Comment by milkypostman** [comment]
ty!
