### ISSUE TITLE
[Question] Packages organization

### ISSUE THREAD

**Issue by nlamirault** [milkypostman/melpa#3412]
hi,
i create a few days a recipe for `sift.el` [1].
Now i've got another file `projectile-sift.el` [2] which can performe search into projectile using sift backend. 
How can i add this recipe ? 
Update sift.el recipe ? Or add another recipe ?
Thanks.

[1] : https://github.com/nlamirault/sift.el
[2] : https://github.com/nlamirault/sift.el/blob/master/projectile-sift.el

**Comment by milkypostman** [comment]
The relationship is one recipe per package. So if you want
projectile-siftel added just issue a PR with recipe for that package.
Projectile-siftel should have siftel and projectile as dependencies.

**Comment by nlamirault** [comment]
Ok Thanks.
