### ISSUE TITLE
traad-autocomplete looks to be missing from the traad repo

### ISSUE THREAD

**Issue by milkypostman** [milkypostman/melpa#3440]
@yasuyk @abingham looks like something changes in the traad repo. what should we do with `traad-autocomplete`?

**Comment by abingham** [comment]
traad has been split into traad (just the python server component) and emacs-traad (the emacs client code). `traad-autocomplete` was initially in emacs-traad, but I removed it since, as far as I know, it's obsolete.

**Comment by milkypostman** [comment]
@abingham so I should just remove the recipe?

**Comment by abingham** [comment]
Oh, yes. Sorry. I had forgotten about that.

**Comment by milkypostman** [comment]
tyvm
