### ISSUE TITLE
How to use it programmatically ?

### ISSUE THREAD

**Issue by azer** [milkypostman/melpa#3457]
I'd like to automate installing all the packages. The documentation doesn't mention any Elisp functions to install libraries, or, am I missing ?

**Comment by dunn** [comment]
MELPA is a repository you can add to `package.el`'s list `package-archives`, so all the functions provided by `package.el` can be used to install packages from here.  If you just want to make sure everything in your `emacs.el` is installed you can do something like
```elisp
(defun install-if-not (package)
  (unless (package-installed-p package)
    (package-install package)))
```
If you really want to install everything in MELPA, something like this would work (I haven't tested it, I don't want to install everything in MELPA):
```elisp
(let ((package-archives '(("melpa-stable" . "https://stable.melpa.org/packages/"))))
  (require 'package)
  (package-initialize)

  (cl-loop for recipe in (cdr package-archive-contents)
             do
             (setq recipe (car recipe))
             (package-install recipe)))

**Comment by milkypostman** [comment]
This seems to have been resolved. All this functionality is just part of package.el, you don't need any of innards to do what you would need. But let me know if there is anything else we can do.
