### ISSUE TITLE
How to change Melpa's installation directory ?

### ISSUE THREAD

**Issue by azer** [milkypostman/melpa#3458]
My emacs config directory is different than ".emacs.d" and melpa doesn't load the installed packages. How can I programmatically point emacs to load melpa packages from ~/.emacs/elpa ?

**Comment by purcell** [comment]
See the docs for the variables `package-user-dir` and `package-directory-list` in the built-in `package.el` library. Probably you need to set the former near the beginning of your config, and certainly before calling `package-initialize`.
