### ISSUE TITLE
Changing the request.el repository

### ISSUE THREAD

**Issue by abingham** [milkypostman/melpa#3459]
@tkf seem to have abandoned request.el. There are [important pull requests that have been open for more than a year](https://github.com/tkf/emacs-request/pull/15) that are [having real impacts on other projects](https://github.com/abingham/traad/issues/78). I've made multiple attempts to reach him through email and by tagging him in messages; despite apparently being active on other projects, he hasn't managed to respond.

[I've brought this up with MELPA before](https://github.com/milkypostman/melpa/issues/1994), and I was told (reasonably) to try working with @tkf to make the existing repository work. But he is simply not responding to any communication, so I don't know what recourse I have beyond trying to make a fork of request. If the MELPA project has any leverage with him, perhaps you can get him to do something.

As things stand, though, I would like to propose that I (or someone) fork request.el, apply the outstanding patches, and update the link in MELPA to the fork. Are you at all willing to consider this now?

**Comment by PythonNut** [comment]
+1

If the original maintainer ever does show up, we can switch the repo back, possibly merging the new work on top of his branch if required.

**Comment by milkypostman** [comment]
This is fine with me if you want to fork now. I think you've made reasonable attempts.

**Comment by milkypostman** [comment]
@abingham I assume you will maintain the fork? Feel free to send a PR when you're ready.

**Comment by abingham** [comment]
@milkypostman Yes, I'll maintain it insofar as I can. I don't plan to do any active development on it, but I'll merge in PRs as necessary. And as @PythonNut says, my real hope is that eventually @tkf takes the project over again, at which point we can just redirect MELPA to his repo.

I'll try to get a new repo in place soon. Thanks.
