### ISSUE TITLE
flycheck package ships development files

### ISSUE THREAD

**Issue by marsam** [milkypostman/melpa#3480]
Hi:

The [flycheck](https://github.com/flycheck/flycheck) package mistakenly adds `flycheck-ert.el` and `flycheck-buttercup.el` which are intented for development.

Should be enough to add `*-ert.el` and `*-buttercup.el` to `:exclude` in [`package-build-default-files-spec`](https://github.com/milkypostman/melpa/blob/10bf153/package-build.el#L139-L144)?

**Comment by purcell** [comment]
Thanks, yes, that makes sense to me. Would you like to file a pull request?

**Comment by lunaryorn** [comment]
These files were [deliberately part of Flycheck's package](https://github.com/flycheck/flycheck/blob/fe8b311cd90a7dc5cbfe1548104ca0b9f9212e9f/Cask#L6) to support unit tests in dependent packages.  They should never have been removed, and I would like to ask you to bring them back.  The removal has broken or will break test suites and Travis CI for many dependent packages.

I am surprised, disappointed, and also somewhat angry that changes to Flycheck's package—which is arguably an important one—were made without asking us.

**Comment by lunaryorn** [comment]
I'd hope that in future we're asked before 3rd parties make changes to our package on our behalf, without even asking us for comment.

**Comment by purcell** [comment]
Yep, that was unfortunate, sorry. We also can't always get everything right for all packages. Thanks for helping to correct this: I've reverted the related commit.

**Comment by lunaryorn** [comment]
@purcell Thank you very much :)

**Comment by purcell** [comment]
Should we just make flycheck depend on buttercup? These compilation errors at install time make flycheck look uncharacteristically bad:

```
Compiling file /Users/steve/.emacs.d/elpa/flycheck-20160216.138/flycheck-buttercup.el at Thu Feb 18 08:26:25 2016
Entering directory ‘/Users/steve/.emacs.d/elpa/flycheck-20160216.138/’
flycheck-buttercup.el:39:1:Error: Cannot open load file: No such file or directory, buttercup
```

(I could also imagine a "flycheck-dev" package...)

**Comment by lunaryorn** [comment]
@purcell I don't know.  I tend to ignore these error but then again I'm spoiled by `org-plus-contrib` which runs amok on these warnings.

A separate package feels somewhat involved, and it'd be a MELPA special feature—we couldn't recreate this split package ourselves, because `cask` doesn't support split packages.  This has no practical impact at all, because we don't build packages anyway thanks to MELPA :blush: but still it somehow feels not right :confused:  But neither does a dependency on buttercup…

I really don't know.  If only ELPA had optional dependencies…

**Comment by purcell** [comment]
Yeah, there's no perfect solution, I guess.

**Comment by cpitclaudel** [comment]
I wonder if adding

```
;; Local Variables:
;; no-byte-compile: t
;; End:
```

to `flycheck-buttercup.el` would do. @lunaryorn?

**Comment by purcell** [comment]
@cpitclaudel Seems like a good workaround. :-) Thanks.
