### ISSUE TITLE
bad dependency

### ISSUE THREAD

**Issue by zot** [milkypostman/melpa#3502]
git-commit 20160117.1513 depended on with-editor 20160118 but that version did not exist but that version of git-commit still made it into the melpa repository.

Is the auto-build process supposed to reject package versions with bad dependencies?

**Comment by zot** [comment]
This is in reference to this git-commit issue https://github.com/magit/magit/issues/2497

**Comment by robbyoconnor** [comment]
This is pretty bad...it's not the first time either.

**Comment by zot** [comment]
Just wanted to submit this so it could be fixed if the auto-build is supposed to detect it.  Hopefully melpa snapshots the package information with each build so it can be diagnosed.

**Comment by milkypostman** [comment]
We don't do any dependency checking in the build. We suggest that packages
NOT depend on our version numbers. Packages should bar their dependencies
on STABLE versions of packages. And again that's up to the package
maintainers to be concerned with.

To speed up package builds we do not create dependency graphs but rather
build every package independently.

I'm not sure what should be diagnosed here.

**Comment by robbyoconnor** [comment]
Except that's not how people do things...

**Comment by Silex** [comment]
@milkypostman: a simple workaround would be to NOT allow a user to download a newer version of a package until all the packages were built. A simple building of the new packages into some temporary directory and then replacing all the packages built at once would do that.

**Comment by Silex** [comment]
Just to be clear, AFAIK the problem is not the dependencies it's the fact that a package built is immediatly available... while its dependency is still in the process of being built and thus not available.

**Comment by robbyoconnor** [comment]
That wouldn't help -- since the magit instance was their fault.

**Comment by milkypostman** [comment]
i don't want to get into another discussion about our "broken" version system (#2944) or a discussion about stable vs. bleeding edge (#3306) here.

@Silex there is a tradeoff here which is that with our current system, people see their changes as *soon* as possible. the tradeoff is that there is sometimes a mismatch but over the however many years with nearly 3k packages this *rarely* come up. I think the tradeoff is worth it.

but from what I gather here it's just a matter of the upstream source using the wrong dependencies.
